# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/xdc/zc702_hdmi.xdc

# Block Designs: bd/top/top.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top || ORIG_REF_NAME==top}]

# IP: bd/top/ip/top_util_vector_logic_1_0/top_util_vector_logic_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_util_vector_logic_1_0 || ORIG_REF_NAME==top_util_vector_logic_1_0}]

# IP: bd/top/ip/top_fmc_imageon_hdmi_in_1_0/top_fmc_imageon_hdmi_in_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_fmc_imageon_hdmi_in_1_0 || ORIG_REF_NAME==top_fmc_imageon_hdmi_in_1_0}]

# IP: bd/top/ip/top_v_vid_in_axi4s_1_0/top_v_vid_in_axi4s_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_v_vid_in_axi4s_1_0 || ORIG_REF_NAME==top_v_vid_in_axi4s_1_0}]

# IP: bd/top/ip/top_v_tc_1_0/top_v_tc_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_v_tc_1_0 || ORIG_REF_NAME==top_v_tc_1_0}]

# IP: bd/top/ip/top_vsrc_sel_1_0/top_vsrc_sel_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_vsrc_sel_1_0 || ORIG_REF_NAME==top_vsrc_sel_1_0}]

# IP: bd/top/ip/top_processing_system7_1_0/top_processing_system7_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_processing_system7_1_0 || ORIG_REF_NAME==top_processing_system7_1_0}]

# IP: bd/top/ip/top_v_cresample_1_0/top_v_cresample_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_v_cresample_1_0 || ORIG_REF_NAME==top_v_cresample_1_0}]

# IP: bd/top/ip/top_TPG_VDMA_0/top_TPG_VDMA_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_TPG_VDMA_0 || ORIG_REF_NAME==top_TPG_VDMA_0}]

# IP: bd/top/ip/top_v_ycrcb2rgb_1_0/top_v_ycrcb2rgb_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_v_ycrcb2rgb_1_0 || ORIG_REF_NAME==top_v_ycrcb2rgb_1_0}]

# IP: bd/top/ip/top_axi4_0_0/top_axi4_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_axi4_0_0 || ORIG_REF_NAME==top_axi4_0_0}]

# IP: bd/top/ip/top_axi4_lite_1/top_axi4_lite_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_axi4_lite_1 || ORIG_REF_NAME==top_axi4_lite_1}]

# IP: bd/top/ip/top_xlconstant_one_0/top_xlconstant_one_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_xlconstant_one_0 || ORIG_REF_NAME==top_xlconstant_one_0}]

# IP: bd/top/ip/top_xlconstant_zero_1/top_xlconstant_zero_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_xlconstant_zero_1 || ORIG_REF_NAME==top_xlconstant_zero_1}]

# IP: bd/top/ip/top_proc_sys_reset_0_0/top_proc_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_proc_sys_reset_0_0 || ORIG_REF_NAME==top_proc_sys_reset_0_0}]

# IP: bd/top/ip/top_vid_sel_0/top_vid_sel_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_vid_sel_0 || ORIG_REF_NAME==top_vid_sel_0}]

# IP: bd/top/ip/top_tpg_rst1_1/top_tpg_rst1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_tpg_rst1_1 || ORIG_REF_NAME==top_tpg_rst1_1}]

# IP: bd/top/ip/top_v_tpg_1_0/top_v_tpg_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_v_tpg_1_0 || ORIG_REF_NAME==top_v_tpg_1_0}]

# IP: bd/top/ip/top_xlconcat_3_0/top_xlconcat_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_xlconcat_3_0 || ORIG_REF_NAME==top_xlconcat_3_0}]

# IP: bd/top/ip/top_vbuff_1/top_vbuff_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_vbuff_1 || ORIG_REF_NAME==top_vbuff_1}]

# IP: bd/top/ip/top_tpg_rst_2/top_tpg_rst_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_tpg_rst_2 || ORIG_REF_NAME==top_tpg_rst_2}]

# IP: bd/top/ip/top_xlconcat_2_2/top_xlconcat_2_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_xlconcat_2_2 || ORIG_REF_NAME==top_xlconcat_2_2}]

# IP: bd/top/ip/top_util_reduced_logic_1_0/top_util_reduced_logic_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_util_reduced_logic_1_0 || ORIG_REF_NAME==top_util_reduced_logic_1_0}]

# IP: bd/top/ip/top_tpg_util_flipflop_1_0/top_tpg_util_flipflop_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_tpg_util_flipflop_1_0 || ORIG_REF_NAME==top_tpg_util_flipflop_1_0}]

# IP: bd/top/ip/top_xlslice_15downto8_3/top_xlslice_15downto8_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_xlslice_15downto8_3 || ORIG_REF_NAME==top_xlslice_15downto8_3}]

# IP: bd/top/ip/top_xlslice_7downto0_4/top_xlslice_7downto0_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_xlslice_7downto0_4 || ORIG_REF_NAME==top_xlslice_7downto0_4}]

# IP: bd/top/ip/top_xlconcat_1_3/top_xlconcat_1_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_xlconcat_1_3 || ORIG_REF_NAME==top_xlconcat_1_3}]

# IP: bd/top/ip/top_clk_wiz_2_0/top_clk_wiz_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_clk_wiz_2_0 || ORIG_REF_NAME==top_clk_wiz_2_0}]

# IP: bd/top/ip/top_xlconstant_3_3/top_xlconstant_3_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_xlconstant_3_3 || ORIG_REF_NAME==top_xlconstant_3_3}]

# IP: bd/top/ip/top_xlconstant_4_4/top_xlconstant_4_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_xlconstant_4_4 || ORIG_REF_NAME==top_xlconstant_4_4}]

# IP: bd/top/ip/top_xlconstant_5_5/top_xlconstant_5_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_xlconstant_5_5 || ORIG_REF_NAME==top_xlconstant_5_5}]

# IP: bd/top/ip/top_xlconstant_6_6/top_xlconstant_6_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_xlconstant_6_6 || ORIG_REF_NAME==top_xlconstant_6_6}]

# IP: bd/top/ip/top_xlslice_1_8/top_xlslice_1_8.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_xlslice_1_8 || ORIG_REF_NAME==top_xlslice_1_8}]

# IP: bd/top/ip/top_logicvc_1_0/top_logicvc_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_logicvc_1_0 || ORIG_REF_NAME==top_logicvc_1_0}]

# IP: bd/top/ip/top_binary_to_grey_1_0/top_binary_to_grey_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_binary_to_grey_1_0 || ORIG_REF_NAME==top_binary_to_grey_1_0}]

# IP: bd/top/ip/top_proc_sys_reset_2_1/top_proc_sys_reset_2_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_proc_sys_reset_2_1 || ORIG_REF_NAME==top_proc_sys_reset_2_1}]

# IP: bd/top/ip/top_proc_sys_reset_3_2/top_proc_sys_reset_3_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_proc_sys_reset_3_2 || ORIG_REF_NAME==top_proc_sys_reset_3_2}]

# IP: bd/top/ip/top_proc_sys_reset_1_3/top_proc_sys_reset_1_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_proc_sys_reset_1_3 || ORIG_REF_NAME==top_proc_sys_reset_1_3}]

# IP: bd/top/ip/top_xlslice_2_9/top_xlslice_2_9.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_xlslice_2_9 || ORIG_REF_NAME==top_xlslice_2_9}]

# IP: bd/top/ip/top_axis_subset_converter_0_0/top_axis_subset_converter_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_axis_subset_converter_0_0 || ORIG_REF_NAME==top_axis_subset_converter_0_0}]

# IP: bd/top/ip/top_xlconstant_0_0/top_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_xlconstant_0_0 || ORIG_REF_NAME==top_xlconstant_0_0}]

# IP: bd/top/ip/top_xbar_1/top_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_xbar_1 || ORIG_REF_NAME==top_xbar_1}]

# IP: bd/top/ip/top_xbar_0/top_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_xbar_0 || ORIG_REF_NAME==top_xbar_0}]

# IP: bd/top/ip/top_datamover_0_0/top_datamover_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_datamover_0_0 || ORIG_REF_NAME==top_datamover_0_0}]

# IP: bd/top/ip/top_img_process_0_0/top_img_process_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_img_process_0_0 || ORIG_REF_NAME==top_img_process_0_0}]

# IP: bd/top/ip/top_img_process_0_if_0/top_img_process_0_if_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_img_process_0_if_0 || ORIG_REF_NAME==top_img_process_0_if_0}]

# IP: bd/top/ip/top_axi_interconnect_M_AXI_GP1_0/top_axi_interconnect_M_AXI_GP1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_axi_interconnect_M_AXI_GP1_0 || ORIG_REF_NAME==top_axi_interconnect_M_AXI_GP1_0}]

# IP: bd/top/ip/top_xbar_2/top_xbar_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_xbar_2 || ORIG_REF_NAME==top_xbar_2}]

# IP: bd/top/ip/top_axi_interconnect_S_AXI_HP1_0/top_axi_interconnect_S_AXI_HP1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_axi_interconnect_S_AXI_HP1_0 || ORIG_REF_NAME==top_axi_interconnect_S_AXI_HP1_0}]

# IP: bd/top/ip/top_xbar_3/top_xbar_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_xbar_3 || ORIG_REF_NAME==top_xbar_3}]

# IP: bd/top/ip/top_axis_rtr_datamover_0_0_1/top_axis_rtr_datamover_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_axis_rtr_datamover_0_0 || ORIG_REF_NAME==top_axis_rtr_datamover_0_0}]

# IP: bd/top/ip/top_s00_regslice_0/top_s00_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_s00_regslice_0 || ORIG_REF_NAME==top_s00_regslice_0}]

# IP: bd/top/ip/top_s00_data_fifo_0_1/top_s00_data_fifo_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_s00_data_fifo_0 || ORIG_REF_NAME==top_s00_data_fifo_0}]

# IP: bd/top/ip/top_s01_regslice_0/top_s01_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_s01_regslice_0 || ORIG_REF_NAME==top_s01_regslice_0}]

# IP: bd/top/ip/top_s01_data_fifo_0/top_s01_data_fifo_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_s01_data_fifo_0 || ORIG_REF_NAME==top_s01_data_fifo_0}]

# IP: bd/top/ip/top_m00_data_fifo_0/top_m00_data_fifo_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_m00_data_fifo_0 || ORIG_REF_NAME==top_m00_data_fifo_0}]

# IP: bd/top/ip/top_m00_regslice_0/top_m00_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_m00_regslice_0 || ORIG_REF_NAME==top_m00_regslice_0}]

# IP: bd/top/ip/top_s00_regslice_1/top_s00_regslice_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_s00_regslice_1 || ORIG_REF_NAME==top_s00_regslice_1}]

# IP: bd/top/ip/top_s00_data_fifo_1/top_s00_data_fifo_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_s00_data_fifo_1 || ORIG_REF_NAME==top_s00_data_fifo_1}]

# IP: bd/top/ip/top_m00_regslice_1/top_m00_regslice_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_m00_regslice_1 || ORIG_REF_NAME==top_m00_regslice_1}]

# IP: bd/top/ip/top_m01_regslice_0/top_m01_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_m01_regslice_0 || ORIG_REF_NAME==top_m01_regslice_0}]

# IP: bd/top/ip/top_s00_regslice_2/top_s00_regslice_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_s00_regslice_2 || ORIG_REF_NAME==top_s00_regslice_2}]

# IP: bd/top/ip/top_s01_regslice_1/top_s01_regslice_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_s01_regslice_1 || ORIG_REF_NAME==top_s01_regslice_1}]

# IP: bd/top/ip/top_s01_data_fifo_1/top_s01_data_fifo_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_s01_data_fifo_1 || ORIG_REF_NAME==top_s01_data_fifo_1}]

# IP: bd/top/ip/top_s02_regslice_0/top_s02_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_s02_regslice_0 || ORIG_REF_NAME==top_s02_regslice_0}]

# IP: bd/top/ip/top_s02_data_fifo_0/top_s02_data_fifo_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_s02_data_fifo_0 || ORIG_REF_NAME==top_s02_data_fifo_0}]

# IP: bd/top/ip/top_m00_data_fifo_1/top_m00_data_fifo_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_m00_data_fifo_1 || ORIG_REF_NAME==top_m00_data_fifo_1}]

# IP: bd/top/ip/top_m00_regslice_2/top_m00_regslice_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_m00_regslice_2 || ORIG_REF_NAME==top_m00_regslice_2}]

# IP: bd/top/ip/top_auto_pc_0_1/top_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_auto_pc_0 || ORIG_REF_NAME==top_auto_pc_0}]

# IP: bd/top/ip/top_auto_pc_1_1/top_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_auto_pc_1 || ORIG_REF_NAME==top_auto_pc_1}]

# IP: bd/top/ip/top_auto_pc_2/top_auto_pc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_auto_pc_2 || ORIG_REF_NAME==top_auto_pc_2}]

# IP: bd/top/ip/top_auto_pc_3/top_auto_pc_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_auto_pc_3 || ORIG_REF_NAME==top_auto_pc_3}]

# IP: bd/top/ip/top_auto_us_df_0_1/top_auto_us_df_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_auto_us_df_0 || ORIG_REF_NAME==top_auto_us_df_0}]

# XDC: bd/top/ip/top_v_vid_in_axi4s_1_0/top_v_vid_in_axi4s_1_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==top_v_vid_in_axi4s_1_0 || ORIG_REF_NAME==top_v_vid_in_axi4s_1_0}] {/inst }]/inst ]]

# XDC: bd/top/ip/top_v_vid_in_axi4s_1_0/top_v_vid_in_axi4s_1_0_ooc.xdc

# XDC: bd/top/ip/top_v_tc_1_0/top_v_tc_1_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==top_v_tc_1_0 || ORIG_REF_NAME==top_v_tc_1_0}] {/U0 }]/U0 ]]

# XDC: bd/top/ip/top_v_tc_1_0/top_v_tc_1_0_ooc.xdc

# XDC: bd/top/ip/top_processing_system7_1_0/top_processing_system7_1_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==top_processing_system7_1_0 || ORIG_REF_NAME==top_processing_system7_1_0}] {/inst }]/inst ]]

# XDC: bd/top/ip/top_v_cresample_1_0/top_v_cresample_1_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==top_v_cresample_1_0 || ORIG_REF_NAME==top_v_cresample_1_0}] {/U0 }]/U0 ]]

# XDC: bd/top/ip/top_v_cresample_1_0/top_v_cresample_1_0_ooc.xdc

# XDC: bd/top/ip/top_TPG_VDMA_0/top_TPG_VDMA_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==top_TPG_VDMA_0 || ORIG_REF_NAME==top_TPG_VDMA_0}] {/U0 }]/U0 ]]

# XDC: bd/top/ip/top_TPG_VDMA_0/top_TPG_VDMA_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==top_TPG_VDMA_0 || ORIG_REF_NAME==top_TPG_VDMA_0}] {/U0 }]/U0 ]]

# XDC: bd/top/ip/top_TPG_VDMA_0/top_TPG_VDMA_0_ooc.xdc

# XDC: bd/top/ip/top_v_ycrcb2rgb_1_0/top_v_ycrcb2rgb_1_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==top_v_ycrcb2rgb_1_0 || ORIG_REF_NAME==top_v_ycrcb2rgb_1_0}] {/U0 }]/U0 ]]

# XDC: bd/top/ip/top_v_ycrcb2rgb_1_0/top_v_ycrcb2rgb_1_0_ooc.xdc

# XDC: bd/top/ip/top_proc_sys_reset_0_0/top_proc_sys_reset_0_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_proc_sys_reset_0_0 || ORIG_REF_NAME==top_proc_sys_reset_0_0}]

# XDC: bd/top/ip/top_proc_sys_reset_0_0/top_proc_sys_reset_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_proc_sys_reset_0_0 || ORIG_REF_NAME==top_proc_sys_reset_0_0}]

# XDC: bd/top/ip/top_proc_sys_reset_0_0/top_proc_sys_reset_0_0_ooc.xdc

# XDC: bd/top/ip/top_v_tpg_1_0/top_v_tpg_1_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==top_v_tpg_1_0 || ORIG_REF_NAME==top_v_tpg_1_0}] {/U0 }]/U0 ]]

# XDC: bd/top/ip/top_v_tpg_1_0/top_v_tpg_1_0_ooc.xdc

# XDC: bd/top/ip/top_clk_wiz_2_0/top_clk_wiz_2_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==top_clk_wiz_2_0 || ORIG_REF_NAME==top_clk_wiz_2_0}] {/inst }]/inst ]]

# XDC: bd/top/ip/top_clk_wiz_2_0/top_clk_wiz_2_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==top_clk_wiz_2_0 || ORIG_REF_NAME==top_clk_wiz_2_0}] {/inst }]/inst ]]

# XDC: bd/top/ip/top_clk_wiz_2_0/top_clk_wiz_2_0_ooc.xdc

# XDC: bd/top/ip/top_proc_sys_reset_2_1/top_proc_sys_reset_2_1_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_proc_sys_reset_2_1 || ORIG_REF_NAME==top_proc_sys_reset_2_1}]

# XDC: bd/top/ip/top_proc_sys_reset_2_1/top_proc_sys_reset_2_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_proc_sys_reset_2_1 || ORIG_REF_NAME==top_proc_sys_reset_2_1}]

# XDC: bd/top/ip/top_proc_sys_reset_2_1/top_proc_sys_reset_2_1_ooc.xdc

# XDC: bd/top/ip/top_proc_sys_reset_3_2/top_proc_sys_reset_3_2_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_proc_sys_reset_3_2 || ORIG_REF_NAME==top_proc_sys_reset_3_2}]

# XDC: bd/top/ip/top_proc_sys_reset_3_2/top_proc_sys_reset_3_2.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_proc_sys_reset_3_2 || ORIG_REF_NAME==top_proc_sys_reset_3_2}]

# XDC: bd/top/ip/top_proc_sys_reset_3_2/top_proc_sys_reset_3_2_ooc.xdc

# XDC: bd/top/ip/top_proc_sys_reset_1_3/top_proc_sys_reset_1_3_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_proc_sys_reset_1_3 || ORIG_REF_NAME==top_proc_sys_reset_1_3}]

# XDC: bd/top/ip/top_proc_sys_reset_1_3/top_proc_sys_reset_1_3.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_proc_sys_reset_1_3 || ORIG_REF_NAME==top_proc_sys_reset_1_3}]

# XDC: bd/top/ip/top_proc_sys_reset_1_3/top_proc_sys_reset_1_3_ooc.xdc

# XDC: bd/top/ip/top_axis_subset_converter_0_0/top_axis_subset_converter_0_0_ooc.xdc

# XDC: bd/top/ip/top_xbar_1/top_xbar_1_ooc.xdc

# XDC: bd/top/ip/top_xbar_0/top_xbar_0_ooc.xdc

# XDC: bd/top/ip/top_datamover_0_0/top_datamover_0_0_ooc.xdc

# XDC: bd/top/ip/top_datamover_0_0/top_datamover_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==top_datamover_0_0 || ORIG_REF_NAME==top_datamover_0_0}] {/U0 }]/U0 ]]

# XDC: bd/top/ip/top_datamover_0_0/top_datamover_0_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==top_datamover_0_0 || ORIG_REF_NAME==top_datamover_0_0}] {/U0 }]/U0 ]]

# XDC: ipshared/xilinx.com/img_process_v1_0/922e0cf7/constraints/img_process_ooc.xdc

# XDC: bd/top/ip/top_img_process_0_if_0/top_img_process_0_if_0_ooc.xdc

# XDC: bd/top/ip/top_img_process_0_if_0/top_img_process_0_if_0_xdc_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==top_img_process_0_if_0 || ORIG_REF_NAME==top_img_process_0_if_0}] {/U0 }]/U0 ]]

# XDC: bd/top/ip/top_img_process_0_if_0/top_img_process_0_if_0_xdc.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==top_img_process_0_if_0 || ORIG_REF_NAME==top_img_process_0_if_0}] {/U0 }]/U0 ]]

# XDC: bd/top/ip/top_xbar_2/top_xbar_2_ooc.xdc

# XDC: bd/top/ip/top_xbar_3/top_xbar_3_ooc.xdc

# XDC: bd/top/ip/top_s00_regslice_0/top_s00_regslice_0_ooc.xdc

# XDC: bd/top/ip/top_s00_data_fifo_0_1/top_s00_data_fifo_0_ooc.xdc

# XDC: bd/top/ip/top_s01_regslice_0/top_s01_regslice_0_ooc.xdc

# XDC: bd/top/ip/top_s01_data_fifo_0/top_s01_data_fifo_0_ooc.xdc

# XDC: bd/top/ip/top_m00_data_fifo_0/top_m00_data_fifo_0_ooc.xdc

# XDC: bd/top/ip/top_m00_regslice_0/top_m00_regslice_0_ooc.xdc

# XDC: bd/top/ip/top_s00_regslice_1/top_s00_regslice_1_ooc.xdc

# XDC: bd/top/ip/top_s00_data_fifo_1/top_s00_data_fifo_1_ooc.xdc

# XDC: bd/top/ip/top_m00_regslice_1/top_m00_regslice_1_ooc.xdc

# XDC: bd/top/ip/top_m01_regslice_0/top_m01_regslice_0_ooc.xdc

# XDC: bd/top/ip/top_s00_regslice_2/top_s00_regslice_2_ooc.xdc

# XDC: bd/top/ip/top_s01_regslice_1/top_s01_regslice_1_ooc.xdc

# XDC: bd/top/ip/top_s01_data_fifo_1/top_s01_data_fifo_1_ooc.xdc

# XDC: bd/top/ip/top_s02_regslice_0/top_s02_regslice_0_ooc.xdc

# XDC: bd/top/ip/top_s02_data_fifo_0/top_s02_data_fifo_0_ooc.xdc

# XDC: bd/top/ip/top_m00_data_fifo_1/top_m00_data_fifo_1_ooc.xdc

# XDC: bd/top/ip/top_m00_regslice_2/top_m00_regslice_2_ooc.xdc

# XDC: bd/top/ip/top_auto_pc_0_1/top_auto_pc_0_ooc.xdc

# XDC: bd/top/ip/top_auto_pc_1_1/top_auto_pc_1_ooc.xdc

# XDC: bd/top/ip/top_auto_pc_2/top_auto_pc_2_ooc.xdc

# XDC: bd/top/ip/top_auto_pc_3/top_auto_pc_3_ooc.xdc

# XDC: bd/top/ip/top_auto_us_df_0_1/top_auto_us_df_0_ooc.xdc

# XDC: bd/top/ip/top_auto_us_df_0_1/top_auto_us_df_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==top_auto_us_df_0 || ORIG_REF_NAME==top_auto_us_df_0}] {/inst }]/inst ]]

# XDC: bd/top/top_ooc.xdc
