# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/student/ml634/2015/samples/platforms/zc702_hdmi/samples/simple_sobel/Release/_sds/p0/ipi/zc702_hdmi.cache/wt [current_project]
set_property parent.project_path /home/student/ml634/2015/samples/platforms/zc702_hdmi/samples/simple_sobel/Release/_sds/p0/ipi/zc702_hdmi.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:zc702:part0:0.9 [current_project]
set_property ip_repo_paths {
  /home/student/ml634/2015/samples/platforms/zc702_hdmi/samples/simple_sobel/Release/_sds/iprepo/repo
  /home/student/ml634/2015/samples/platforms/zc702_hdmi/samples/simple_sobel/Release/_sds/p0/ipi/zc702_hdmi.ipdefs
  /work/zhang/common/tools/xilinx/SDSoC/2015.2.1/data/ip/xilinx
} [current_project]
add_files /home/student/ml634/2015/samples/platforms/zc702_hdmi/samples/simple_sobel/Release/_sds/p0/ipi/zc702_hdmi.srcs/sources_1/bd/top/top.bd
set_property used_in_implementation false [get_files -all /home/student/ml634/2015/samples/platforms/zc702_hdmi/samples/simple_sobel/Release/_sds/p0/ipi/zc702_hdmi.srcs/sources_1/bd/top/ip/top_v_vid_in_axi4s_1_0/top_v_vid_in_axi4s_1_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/student/ml634/2015/samples/platforms/zc702_hdmi/samples/simple_sobel/Release/_sds/p0/ipi/zc702_hdmi.srcs/sources_1/bd/top/ip/top_v_vid_in_axi4s_1_0/top_v_vid_in_axi4s_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/student/ml634/2015/samples/platforms/zc702_hdmi/samples/simple_sobel/Release/_sds/p0/ipi/zc702_hdmi.srcs/sources_1/bd/top/ip/top_v_tc_1_0/top_v_tc_1_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/student/ml634/2015/samples/platforms/zc702_hdmi/samples/simple_sobel/Release/_sds/p0/ipi/zc702_hdmi.srcs/sources_1/bd/top/ip/top_v_tc_1_0/top_v_tc_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/student/ml634/2015/samples/platforms/zc702_hdmi/samples/simple_sobel/Release/_sds/p0/ipi/zc702_hdmi.srcs/sources_1/bd/top/ip/top_processing_system7_1_0/top_processing_system7_1_0.xdc]
set_property used_in_implementation false [get_files -all /home/student/ml634/2015/samples/platforms/zc702_hdmi/samples/simple_sobel/Release/_sds/p0/ipi/zc702_hdmi.srcs/sources_1/bd/top/ip/top_v_cresample_1_0/top_v_cresample_1_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/student/ml634/2015/samples/platforms/zc702_hdmi/samples/simple_sobel/Release/_sds/p0/ipi/zc702_hdmi.srcs/sources_1/bd/top/ip/top_v_cresample_1_0/top_v_cresample_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/student/ml634/2015/samples/platforms/zc702_hdmi/samples/simple_sobel/Release/_sds/p0/ipi/zc702_hdmi.srcs/sources_1/bd/top/ip/top_TPG_VDMA_0/top_TPG_VDMA_0.xdc]
set_property used_in_implementation false [get_files -all /home/student/ml634/2015/samples/platforms/zc702_hdmi/samples/simple_sobel/Release/_sds/p0/ipi/zc702_hdmi.srcs/sources_1/bd/top/ip/top_TPG_VDMA_0/top_TPG_VDMA_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/student/ml634/2015/samples/platforms/zc702_hdmi/samples/simple_sobel/Release/_sds/p0/ipi/zc702_hdmi.srcs/sources_1/bd/top/ip/top_TPG_VDMA_0/top_TPG_VDMA_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/student/ml634/2015/samples/platforms/zc702_hdmi/samples/simple_sobel/Release/_sds/p0/ipi/zc702_hdmi.srcs/sources_1/bd/top/ip/top_v_ycrcb2rgb_1_0/top_v_ycrcb2rgb_1_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/student/ml634/2015/samples/platforms/zc702_hdmi/samples/simple_sobel/Release/_sds/p0/ipi/zc702_hdmi.srcs/sources_1/bd/top/ip/top_v_ycrcb2rgb_1_0/top_v_ycrcb2rgb_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/student/ml634/2015/samples/platforms/zc702_hdmi/samples/simple_sobel/Release/_sds/p0/ipi/zc702_hdmi.srcs/sources_1/bd/top/ip/top_proc_sys_reset_0_0/top_proc_sys_reset_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/student/ml634/2015/samples/platforms/zc702_hdmi/samples/simple_sobel/Release/_sds/p0/ipi/zc702_hdmi.srcs/sources_1/bd/top/ip/top_proc_sys_reset_0_0/top_proc_sys_reset_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/student/ml634/2015/samples/platforms/zc702_hdmi/samples/simple_sobel/Release/_sds/p0/ipi/zc702_hdmi.srcs/sources_1/bd/top/ip/top_proc_sys_reset_0_0/top_proc_sys_reset_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/student/ml634/2015/samples/platforms/zc702_hdmi/samples/simple_sobel/Release/_sds/p0/ipi/zc702_hdmi.srcs/sources_1/bd/top/ip/top_v_tpg_1_0/top_v_tpg_1_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/student/ml634/2015/samples/platforms/zc702_hdmi/samples/simple_sobel/Release/_sds/p0/ipi/zc702_hdmi.srcs/sources_1/bd/top/ip/top_v_tpg_1_0/top_v_tpg_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/student/ml634/2015/samples/platforms/zc702_hdmi/samples/simple_sobel/Release/_sds/p0/ipi/zc702_hdmi.srcs/sources_1/bd/top/ip/top_clk_wiz_2_0/top_clk_wiz_2_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/student/ml634/2015/samples/platforms/zc702_hdmi/samples/simple_sobel/Release/_sds/p0/ipi/zc702_hdmi.srcs/sources_1/bd/top/ip/top_clk_wiz_2_0/top_clk_wiz_2_0.xdc]
set_property used_in_implementation false [get_files -all /home/student/ml634/2015/samples/platforms/zc702_hdmi/samples/simple_sobel/Release/_sds/p0/ipi/zc702_hdmi.srcs/sources_1/bd/top/ip/top_clk_wiz_2_0/top_clk_wiz_2_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/student/ml634/2015/samples/platforms/zc702_hdmi/samples/simple_sobel/Release/_sds/p0/ipi/zc702_hdmi.srcs/sources_1/bd/top/ip/top_proc_sys_reset_2_1/top_proc_sys_reset_2_1_board.xdc]
set_property used_in_implementation false [get_files -all /home/student/ml634/2015/samples/platforms/zc702_hdmi/samples/simple_sobel/Release/_sds/p0/ipi/zc702_hdmi.srcs/sources_1/bd/top/ip/top_proc_sys_reset_2_1/top_proc_sys_reset_2_1.xdc]
set_property used_in_implementation false [get_files -all /home/student/ml634/2015/samples/platforms/zc702_hdmi/samples/simple_sobel/Release/_sds/p0/ipi/zc702_hdmi.srcs/sources_1/bd/top/ip/top_proc_sys_reset_2_1/top_proc_sys_reset_2_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/student/ml634/2015/samples/platforms/zc702_hdmi/samples/simple_sobel/Release/_sds/p0/ipi/zc702_hdmi.srcs/sources_1/bd/top/ip/top_proc_sys_reset_3_2/top_proc_sys_reset_3_2_board.xdc]
set_property used_in_implementation false [get_files -all /home/student/ml634/2015/samples/platforms/zc702_hdmi/samples/simple_sobel/Release/_sds/p0/ipi/zc702_hdmi.srcs/sources_1/bd/top/ip/top_proc_sys_reset_3_2/top_proc_sys_reset_3_2.xdc]
set_property used_in_implementation false [get_files -all /home/student/ml634/2015/samples/platforms/zc702_hdmi/samples/simple_sobel/Release/_sds/p0/ipi/zc702_hdmi.srcs/sources_1/bd/top/ip/top_proc_sys_reset_3_2/top_proc_sys_reset_3_2_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/student/ml634/2015/samples/platforms/zc702_hdmi/samples/simple_sobel/Release/_sds/p0/ipi/zc702_hdmi.srcs/sources_1/bd/top/ip/top_proc_sys_reset_1_3/top_proc_sys_reset_1_3_board.xdc]
set_property used_in_implementation false [get_files -all /home/student/ml634/2015/samples/platforms/zc702_hdmi/samples/simple_sobel/Release/_sds/p0/ipi/zc702_hdmi.srcs/sources_1/bd/top/ip/top_proc_sys_reset_1_3/top_proc_sys_reset_1_3.xdc]
set_property used_in_implementation false [get_files -all /home/student/ml634/2015/samples/platforms/zc702_hdmi/samples/simple_sobel/Release/_sds/p0/ipi/zc702_hdmi.srcs/sources_1/bd/top/ip/top_proc_sys_reset_1_3/top_proc_sys_reset_1_3_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/student/ml634/2015/samples/platforms/zc702_hdmi/samples/simple_sobel/Release/_sds/p0/ipi/zc702_hdmi.srcs/sources_1/bd/top/ip/top_axis_subset_converter_0_0/top_axis_subset_converter_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/student/ml634/2015/samples/platforms/zc702_hdmi/samples/simple_sobel/Release/_sds/p0/ipi/zc702_hdmi.srcs/sources_1/bd/top/ip/top_xbar_1/top_xbar_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/student/ml634/2015/samples/platforms/zc702_hdmi/samples/simple_sobel/Release/_sds/p0/ipi/zc702_hdmi.srcs/sources_1/bd/top/ip/top_xbar_0/top_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/student/ml634/2015/samples/platforms/zc702_hdmi/samples/simple_sobel/Release/_sds/p0/ipi/zc702_hdmi.srcs/sources_1/bd/top/ip/top_datamover_0_0/top_datamover_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/student/ml634/2015/samples/platforms/zc702_hdmi/samples/simple_sobel/Release/_sds/p0/ipi/zc702_hdmi.srcs/sources_1/bd/top/ip/top_datamover_0_0/top_datamover_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/student/ml634/2015/samples/platforms/zc702_hdmi/samples/simple_sobel/Release/_sds/p0/ipi/zc702_hdmi.srcs/sources_1/bd/top/ip/top_datamover_0_0/top_datamover_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/student/ml634/2015/samples/platforms/zc702_hdmi/samples/simple_sobel/Release/_sds/p0/ipi/zc702_hdmi.srcs/sources_1/ipshared/xilinx.com/img_process_v1_0/922e0cf7/constraints/img_process_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/student/ml634/2015/samples/platforms/zc702_hdmi/samples/simple_sobel/Release/_sds/p0/ipi/zc702_hdmi.srcs/sources_1/bd/top/ip/top_img_process_0_if_0/top_img_process_0_if_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/student/ml634/2015/samples/platforms/zc702_hdmi/samples/simple_sobel/Release/_sds/p0/ipi/zc702_hdmi.srcs/sources_1/bd/top/ip/top_img_process_0_if_0/top_img_process_0_if_0_xdc_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/student/ml634/2015/samples/platforms/zc702_hdmi/samples/simple_sobel/Release/_sds/p0/ipi/zc702_hdmi.srcs/sources_1/bd/top/ip/top_img_process_0_if_0/top_img_process_0_if_0_xdc.xdc]
set_property used_in_implementation false [get_files -all /home/student/ml634/2015/samples/platforms/zc702_hdmi/samples/simple_sobel/Release/_sds/p0/ipi/zc702_hdmi.srcs/sources_1/bd/top/ip/top_xbar_2/top_xbar_2_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/student/ml634/2015/samples/platforms/zc702_hdmi/samples/simple_sobel/Release/_sds/p0/ipi/zc702_hdmi.srcs/sources_1/bd/top/ip/top_xbar_3/top_xbar_3_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/student/ml634/2015/samples/platforms/zc702_hdmi/samples/simple_sobel/Release/_sds/p0/ipi/zc702_hdmi.srcs/sources_1/bd/top/ip/top_s00_regslice_0/top_s00_regslice_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/student/ml634/2015/samples/platforms/zc702_hdmi/samples/simple_sobel/Release/_sds/p0/ipi/zc702_hdmi.srcs/sources_1/bd/top/ip/top_s00_data_fifo_0_1/top_s00_data_fifo_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/student/ml634/2015/samples/platforms/zc702_hdmi/samples/simple_sobel/Release/_sds/p0/ipi/zc702_hdmi.srcs/sources_1/bd/top/ip/top_s01_regslice_0/top_s01_regslice_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/student/ml634/2015/samples/platforms/zc702_hdmi/samples/simple_sobel/Release/_sds/p0/ipi/zc702_hdmi.srcs/sources_1/bd/top/ip/top_s01_data_fifo_0/top_s01_data_fifo_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/student/ml634/2015/samples/platforms/zc702_hdmi/samples/simple_sobel/Release/_sds/p0/ipi/zc702_hdmi.srcs/sources_1/bd/top/ip/top_m00_data_fifo_0/top_m00_data_fifo_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/student/ml634/2015/samples/platforms/zc702_hdmi/samples/simple_sobel/Release/_sds/p0/ipi/zc702_hdmi.srcs/sources_1/bd/top/ip/top_m00_regslice_0/top_m00_regslice_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/student/ml634/2015/samples/platforms/zc702_hdmi/samples/simple_sobel/Release/_sds/p0/ipi/zc702_hdmi.srcs/sources_1/bd/top/ip/top_s00_regslice_1/top_s00_regslice_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/student/ml634/2015/samples/platforms/zc702_hdmi/samples/simple_sobel/Release/_sds/p0/ipi/zc702_hdmi.srcs/sources_1/bd/top/ip/top_s00_data_fifo_1/top_s00_data_fifo_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/student/ml634/2015/samples/platforms/zc702_hdmi/samples/simple_sobel/Release/_sds/p0/ipi/zc702_hdmi.srcs/sources_1/bd/top/ip/top_m00_regslice_1/top_m00_regslice_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/student/ml634/2015/samples/platforms/zc702_hdmi/samples/simple_sobel/Release/_sds/p0/ipi/zc702_hdmi.srcs/sources_1/bd/top/ip/top_m01_regslice_0/top_m01_regslice_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/student/ml634/2015/samples/platforms/zc702_hdmi/samples/simple_sobel/Release/_sds/p0/ipi/zc702_hdmi.srcs/sources_1/bd/top/ip/top_s00_regslice_2/top_s00_regslice_2_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/student/ml634/2015/samples/platforms/zc702_hdmi/samples/simple_sobel/Release/_sds/p0/ipi/zc702_hdmi.srcs/sources_1/bd/top/ip/top_s01_regslice_1/top_s01_regslice_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/student/ml634/2015/samples/platforms/zc702_hdmi/samples/simple_sobel/Release/_sds/p0/ipi/zc702_hdmi.srcs/sources_1/bd/top/ip/top_s01_data_fifo_1/top_s01_data_fifo_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/student/ml634/2015/samples/platforms/zc702_hdmi/samples/simple_sobel/Release/_sds/p0/ipi/zc702_hdmi.srcs/sources_1/bd/top/ip/top_s02_regslice_0/top_s02_regslice_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/student/ml634/2015/samples/platforms/zc702_hdmi/samples/simple_sobel/Release/_sds/p0/ipi/zc702_hdmi.srcs/sources_1/bd/top/ip/top_s02_data_fifo_0/top_s02_data_fifo_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/student/ml634/2015/samples/platforms/zc702_hdmi/samples/simple_sobel/Release/_sds/p0/ipi/zc702_hdmi.srcs/sources_1/bd/top/ip/top_m00_data_fifo_1/top_m00_data_fifo_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/student/ml634/2015/samples/platforms/zc702_hdmi/samples/simple_sobel/Release/_sds/p0/ipi/zc702_hdmi.srcs/sources_1/bd/top/ip/top_m00_regslice_2/top_m00_regslice_2_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/student/ml634/2015/samples/platforms/zc702_hdmi/samples/simple_sobel/Release/_sds/p0/ipi/zc702_hdmi.srcs/sources_1/bd/top/ip/top_auto_pc_0_1/top_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/student/ml634/2015/samples/platforms/zc702_hdmi/samples/simple_sobel/Release/_sds/p0/ipi/zc702_hdmi.srcs/sources_1/bd/top/ip/top_auto_pc_1_1/top_auto_pc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/student/ml634/2015/samples/platforms/zc702_hdmi/samples/simple_sobel/Release/_sds/p0/ipi/zc702_hdmi.srcs/sources_1/bd/top/ip/top_auto_pc_2/top_auto_pc_2_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/student/ml634/2015/samples/platforms/zc702_hdmi/samples/simple_sobel/Release/_sds/p0/ipi/zc702_hdmi.srcs/sources_1/bd/top/ip/top_auto_pc_3/top_auto_pc_3_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/student/ml634/2015/samples/platforms/zc702_hdmi/samples/simple_sobel/Release/_sds/p0/ipi/zc702_hdmi.srcs/sources_1/bd/top/ip/top_auto_us_df_0_1/top_auto_us_df_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/student/ml634/2015/samples/platforms/zc702_hdmi/samples/simple_sobel/Release/_sds/p0/ipi/zc702_hdmi.srcs/sources_1/bd/top/ip/top_auto_us_df_0_1/top_auto_us_df_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/student/ml634/2015/samples/platforms/zc702_hdmi/samples/simple_sobel/Release/_sds/p0/ipi/zc702_hdmi.srcs/sources_1/bd/top/top_ooc.xdc]
set_property is_locked true [get_files /home/student/ml634/2015/samples/platforms/zc702_hdmi/samples/simple_sobel/Release/_sds/p0/ipi/zc702_hdmi.srcs/sources_1/bd/top/top.bd]

read_verilog -library xil_defaultlib /home/student/ml634/2015/samples/platforms/zc702_hdmi/samples/simple_sobel/Release/_sds/p0/ipi/zc702_hdmi.srcs/sources_1/imports/wrapper/zc702_hdmi_wrapper.v
read_xdc /home/student/ml634/2015/samples/platforms/zc702_hdmi/samples/simple_sobel/Release/_sds/p0/ipi/zc702_hdmi.srcs/constrs_1/imports/xdc/zc702_hdmi.xdc
set_property used_in_implementation false [get_files /home/student/ml634/2015/samples/platforms/zc702_hdmi/samples/simple_sobel/Release/_sds/p0/ipi/zc702_hdmi.srcs/constrs_1/imports/xdc/zc702_hdmi.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
synth_design -top top_wrapper -part xc7z020clg484-1
write_checkpoint -noxdef top_wrapper.dcp
catch { report_utilization -file top_wrapper_utilization_synth.rpt -pb top_wrapper_utilization_synth.pb }
