# ==============================================================
# File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
# Version: 2015.2_hlssdsoc
# Copyright (C) 2015 Xilinx Inc. All rights reserved.
# 
# ==============================================================


/work/zhang/common/tools/xilinx/SDSoC/2015.2.1/Vivado_HLS/2015.2/../../Vivado/2015.2/bin/vivado  -notrace -mode batch -source ipi_example.tcl -tclargs xc7z020clg484-1 ../xilinx_com_hls_img_process_1_0.zip
