// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.2_hlssdsoc
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="img_process,hls_ip_2015_2_hlssdsoc,{HLS_INPUT_TYPE=c,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020clg484-1,HLS_INPUT_CLOCK=5.950000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=5.050000,HLS_SYN_LAT=21687431,HLS_SYN_TPT=none,HLS_SYN_MEM=4,HLS_SYN_DSP=3,HLS_SYN_FF=581,HLS_SYN_LUT=795}" *)

module img_process (
        ap_clk,
        ap_rst_n,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        rgb_data_in_dout,
        rgb_data_in_empty_n,
        rgb_data_in_read,
        rgb_data_out_din,
        rgb_data_out_full_n,
        rgb_data_out_write,
        isobelInvert,
        iminsobelSensitivity,
        imaxsobelSensitivity
);

parameter    ap_const_logic_1 = 1'b1;
parameter    ap_const_logic_0 = 1'b0;
parameter    ap_ST_st1_fsm_0 = 24'b1;
parameter    ap_ST_pp0_stg0_fsm_1 = 24'b10;
parameter    ap_ST_pp0_stg1_fsm_2 = 24'b100;
parameter    ap_ST_pp0_stg2_fsm_3 = 24'b1000;
parameter    ap_ST_pp1_stg0_fsm_4 = 24'b10000;
parameter    ap_ST_pp1_stg1_fsm_5 = 24'b100000;
parameter    ap_ST_pp1_stg2_fsm_6 = 24'b1000000;
parameter    ap_ST_pp2_stg0_fsm_7 = 24'b10000000;
parameter    ap_ST_st18_fsm_8 = 24'b100000000;
parameter    ap_ST_st19_fsm_9 = 24'b1000000000;
parameter    ap_ST_pp3_stg0_fsm_10 = 24'b10000000000;
parameter    ap_ST_pp3_stg1_fsm_11 = 24'b100000000000;
parameter    ap_ST_pp3_stg2_fsm_12 = 24'b1000000000000;
parameter    ap_ST_st27_fsm_13 = 24'b10000000000000;
parameter    ap_ST_pp4_stg0_fsm_14 = 24'b100000000000000;
parameter    ap_ST_pp4_stg1_fsm_15 = 24'b1000000000000000;
parameter    ap_ST_pp4_stg2_fsm_16 = 24'b10000000000000000;
parameter    ap_ST_pp4_stg3_fsm_17 = 24'b100000000000000000;
parameter    ap_ST_st39_fsm_18 = 24'b1000000000000000000;
parameter    ap_ST_st40_fsm_19 = 24'b10000000000000000000;
parameter    ap_ST_st41_fsm_20 = 24'b100000000000000000000;
parameter    ap_ST_st42_fsm_21 = 24'b1000000000000000000000;
parameter    ap_ST_pp5_stg0_fsm_22 = 24'b10000000000000000000000;
parameter    ap_ST_st45_fsm_23 = 24'b100000000000000000000000;
parameter    ap_const_lv32_0 = 32'b00000000000000000000000000000000;
parameter    ap_const_lv1_1 = 1'b1;
parameter    ap_const_lv32_1 = 32'b1;
parameter    ap_const_lv32_A = 32'b1010;
parameter    ap_const_lv1_0 = 1'b0;
parameter    ap_const_lv32_4 = 32'b100;
parameter    ap_const_lv32_F = 32'b1111;
parameter    ap_const_lv32_11 = 32'b10001;
parameter    ap_const_lv32_14 = 32'b10100;
parameter    ap_const_lv32_3 = 32'b11;
parameter    ap_const_lv32_2 = 32'b10;
parameter    ap_const_lv32_6 = 32'b110;
parameter    ap_const_lv32_5 = 32'b101;
parameter    ap_const_lv32_7 = 32'b111;
parameter    ap_const_lv32_8 = 32'b1000;
parameter    ap_const_lv32_9 = 32'b1001;
parameter    ap_const_lv32_C = 32'b1100;
parameter    ap_const_lv32_B = 32'b1011;
parameter    ap_const_lv32_E = 32'b1110;
parameter    ap_const_lv32_10 = 32'b10000;
parameter    ap_const_lv32_13 = 32'b10011;
parameter    ap_const_lv32_16 = 32'b10110;
parameter    ap_const_lv32_D = 32'b1101;
parameter    ap_const_lv12_0 = 12'b000000000000;
parameter    ap_const_lv11_2 = 11'b10;
parameter    ap_const_lv11_1 = 11'b1;
parameter    ap_const_lv11_0 = 11'b00000000000;
parameter    ap_const_lv32_12 = 32'b10010;
parameter    ap_const_lv32_15 = 32'b10101;
parameter    ap_const_lv32_17 = 32'b10111;
parameter    ap_const_lv12_800 = 12'b100000000000;
parameter    ap_const_lv12_1 = 12'b1;
parameter    ap_const_lv6_0 = 6'b000000;
parameter    ap_const_lv9_80 = 9'b10000000;
parameter    ap_const_lv7_0 = 7'b0000000;
parameter    ap_const_lv8_10 = 8'b10000;
parameter    ap_const_lv8_FF = 8'b11111111;
parameter    ap_const_lv8_0 = 8'b00000000;
parameter    ap_const_lv11_438 = 11'b10000111000;
parameter    ap_const_lv20_1 = 20'b1;
parameter    ap_const_lv11_7FE = 11'b11111111110;
parameter    ap_const_lv11_7FF = 11'b11111111111;
parameter    ap_const_lv21_1 = 21'b1;
parameter    ap_const_lv21_2 = 21'b10;
parameter    ap_const_lv12_FF = 12'b11111111;
parameter    ap_const_lv11_780 = 11'b11110000000;
parameter    ap_const_lv13_19 = 13'b11001;
parameter    ap_true = 1'b1;

input   ap_clk;
input   ap_rst_n;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] rgb_data_in_dout;
input   rgb_data_in_empty_n;
output   rgb_data_in_read;
output  [31:0] rgb_data_out_din;
input   rgb_data_out_full_n;
output   rgb_data_out_write;
input  [31:0] isobelInvert;
input  [31:0] iminsobelSensitivity;
input  [31:0] imaxsobelSensitivity;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg rgb_data_in_read;
reg[31:0] rgb_data_out_din;
reg rgb_data_out_write;
reg    ap_rst_n_inv;
(* fsm_encoding = "none" *) reg   [23:0] ap_CS_fsm = 24'b1;
reg    ap_sig_cseq_ST_st1_fsm_0;
reg    ap_sig_bdd_42;
reg   [12:0] line_buffer_address0;
reg    line_buffer_ce0;
reg    line_buffer_we0;
reg   [7:0] line_buffer_d0;
wire   [7:0] line_buffer_q0;
reg   [12:0] line_buffer_address1;
reg    line_buffer_ce1;
reg    line_buffer_we1;
wire   [7:0] line_buffer_d1;
wire   [7:0] line_buffer_q1;
reg   [11:0] pix_j_reg_295;
reg   [11:0] ap_reg_ppstg_pix_j_reg_295_pp0_it1;
reg    ap_sig_cseq_ST_pp0_stg0_fsm_1;
reg    ap_sig_bdd_83;
reg    ap_reg_ppiten_pp0_it0 = 1'b0;
reg    ap_reg_ppiten_pp0_it1 = 1'b0;
reg    ap_reg_ppiten_pp0_it2 = 1'b0;
reg   [11:0] pix_j_1_reg_307;
reg   [11:0] p_01_rec_reg_318;
reg   [11:0] pix_j_3_reg_341;
reg   [11:0] ap_reg_ppstg_pix_j_3_reg_341_pp3_it1;
reg    ap_sig_cseq_ST_pp3_stg0_fsm_10;
reg    ap_sig_bdd_103;
reg    ap_reg_ppiten_pp3_it0 = 1'b0;
reg    ap_reg_ppiten_pp3_it1 = 1'b0;
reg    ap_reg_ppiten_pp3_it2 = 1'b0;
reg   [10:0] pix_j_4_reg_353;
reg   [10:0] p_12_pn_rec_reg_365;
reg   [11:0] p_34_rec_reg_388;
reg   [7:0] reg_427;
reg   [0:0] exitcond_reg_1284;
reg    ap_sig_cseq_ST_pp1_stg0_fsm_4;
reg    ap_sig_bdd_128;
reg    ap_reg_ppiten_pp1_it0 = 1'b0;
reg    ap_reg_ppiten_pp1_it1 = 1'b0;
reg    ap_reg_ppiten_pp1_it2 = 1'b0;
reg   [0:0] exitcond1_reg_1313;
reg   [0:0] exitcond4_reg_1365;
reg   [7:0] reg_431;
reg    ap_sig_cseq_ST_pp4_stg1_fsm_15;
reg    ap_sig_bdd_150;
reg    ap_reg_ppiten_pp4_it0 = 1'b0;
reg    ap_reg_ppiten_pp4_it1 = 1'b0;
reg    ap_reg_ppiten_pp4_it2 = 1'b0;
reg   [0:0] exitcond6_reg_1394;
reg    ap_sig_cseq_ST_pp4_stg3_fsm_17;
reg    ap_sig_bdd_166;
reg    ap_sig_cseq_ST_st41_fsm_20;
reg    ap_sig_bdd_174;
reg   [7:0] reg_437;
wire   [0:0] exitcond_fu_443_p2;
reg   [0:0] ap_reg_ppstg_exitcond_reg_1284_pp0_it1;
wire   [11:0] pix_j_2_fu_449_p2;
reg   [11:0] pix_j_2_reg_1288;
reg    ap_sig_cseq_ST_pp0_stg2_fsm_3;
reg    ap_sig_bdd_200;
wire   [14:0] tmp6_fu_491_p2;
reg   [14:0] tmp6_reg_1298;
reg    ap_sig_cseq_ST_pp0_stg1_fsm_2;
reg    ap_sig_bdd_210;
reg    ap_sig_bdd_214;
wire   [12:0] grp_fu_1255_p3;
reg   [12:0] tmp9_reg_1303;
reg   [7:0] tmp_i_reg_1308;
wire   [0:0] exitcond1_fu_558_p2;
reg   [0:0] ap_reg_ppstg_exitcond1_reg_1313_pp1_it1;
wire   [11:0] pix_j_6_fu_564_p2;
reg   [11:0] pix_j_6_reg_1317;
wire   [11:0] line_buffer_addr1_fu_570_p2;
reg   [11:0] line_buffer_addr1_reg_1322;
reg   [11:0] ap_reg_ppstg_line_buffer_addr1_reg_1322_pp1_it1;
reg    ap_sig_cseq_ST_pp1_stg2_fsm_6;
reg    ap_sig_bdd_244;
wire   [14:0] tmp5_fu_612_p2;
reg   [14:0] tmp5_reg_1332;
reg    ap_sig_cseq_ST_pp1_stg1_fsm_5;
reg    ap_sig_bdd_254;
reg    ap_sig_bdd_257;
wire   [12:0] grp_fu_1247_p3;
reg   [12:0] tmp12_reg_1337;
reg   [7:0] tmp_i1_reg_1342;
wire   [0:0] exitcond2_fu_678_p2;
reg   [0:0] exitcond2_reg_1347;
reg    ap_sig_cseq_ST_pp2_stg0_fsm_7;
reg    ap_sig_bdd_275;
reg    ap_reg_ppiten_pp2_it0 = 1'b0;
reg    ap_sig_bdd_282;
reg    ap_reg_ppiten_pp2_it1 = 1'b0;
wire   [11:0] p_rec3_fu_684_p2;
wire   [7:0] tmp_9_cast_fu_695_p3;
reg   [7:0] tmp_9_cast_reg_1356;
reg    ap_sig_cseq_ST_st18_fsm_8;
reg    ap_sig_bdd_299;
wire   [0:0] exitcond3_fu_703_p2;
reg    ap_sig_cseq_ST_st19_fsm_9;
reg    ap_sig_bdd_308;
wire   [0:0] exitcond4_fu_709_p2;
reg   [0:0] ap_reg_ppstg_exitcond4_reg_1365_pp3_it1;
wire   [11:0] pix_j_7_fu_715_p2;
reg   [11:0] pix_j_7_reg_1369;
reg    ap_sig_cseq_ST_pp3_stg2_fsm_12;
reg    ap_sig_bdd_323;
wire   [14:0] tmp14_fu_757_p2;
reg   [14:0] tmp14_reg_1379;
reg    ap_sig_cseq_ST_pp3_stg1_fsm_11;
reg    ap_sig_bdd_333;
reg    ap_sig_bdd_336;
wire   [12:0] grp_fu_1239_p3;
reg   [12:0] tmp17_reg_1384;
reg   [7:0] tmp_i2_reg_1389;
wire   [0:0] exitcond6_fu_832_p2;
reg    ap_sig_cseq_ST_pp4_stg0_fsm_14;
reg    ap_sig_bdd_353;
reg   [0:0] ap_reg_ppstg_exitcond6_reg_1394_pp4_it1;
reg   [0:0] ap_reg_ppstg_exitcond6_reg_1394_pp4_it2;
wire   [10:0] p_23_rec_fu_838_p2;
reg   [10:0] p_23_rec_reg_1398;
wire  signed [10:0] tmp_12_fu_844_p2;
reg  signed [10:0] tmp_12_reg_1403;
wire   [10:0] pix_j_9_fu_855_p2;
reg   [10:0] pix_j_9_reg_1414;
reg    ap_sig_cseq_ST_pp4_stg2_fsm_16;
reg    ap_sig_bdd_383;
reg    ap_sig_bdd_387;
wire   [8:0] tmp_fu_910_p2;
reg   [8:0] tmp_reg_1441;
wire  signed [10:0] tmp_19_fu_957_p2;
reg  signed [10:0] tmp_19_reg_1451;
wire   [8:0] tmp_21_fu_981_p2;
reg   [8:0] tmp_21_reg_1466;
wire  signed [10:0] x_weight_fu_1008_p2;
reg  signed [10:0] x_weight_reg_1471;
wire   [8:0] tmp2_fu_1022_p2;
reg   [8:0] tmp2_reg_1478;
wire   [9:0] tmp_24_fu_1037_p2;
reg   [9:0] tmp_24_reg_1483;
wire  signed [10:0] y_weight_fu_1057_p2;
reg  signed [10:0] y_weight_reg_1488;
wire   [10:0] x_weight_1_fu_1073_p3;
reg   [10:0] x_weight_1_reg_1494;
wire   [0:0] tmp_27_fu_1080_p2;
reg   [0:0] tmp_27_reg_1499;
wire  signed [11:0] edge_weight_fu_1104_p2;
reg  signed [11:0] edge_weight_reg_1504;
wire   [7:0] tmp_39_fu_1110_p1;
reg   [7:0] tmp_39_reg_1509;
wire   [7:0] edge_val1_fu_1124_p3;
reg   [7:0] edge_val1_reg_1514;
wire   [0:0] tmp_32_fu_1135_p2;
reg   [0:0] tmp_32_reg_1520;
wire   [0:0] tmp_33_fu_1140_p2;
reg   [0:0] tmp_33_reg_1526;
wire   [7:0] edge_val_1_fu_1163_p2;
reg   [7:0] edge_val_1_reg_1531;
wire   [10:0] pix_j_8_fu_1184_p2;
reg   [10:0] pix_j_8_reg_1541;
reg    ap_sig_cseq_ST_st40_fsm_19;
reg    ap_sig_bdd_442;
reg   [12:0] line_buffer_addr_11_reg_1546;
wire   [0:0] exitcond5_fu_1178_p2;
wire   [10:0] pix_i_1_fu_1216_p2;
wire   [0:0] exitcond8_fu_1227_p2;
reg   [0:0] exitcond8_reg_1562;
reg    ap_sig_cseq_ST_pp5_stg0_fsm_22;
reg    ap_sig_bdd_462;
reg    ap_reg_ppiten_pp5_it0 = 1'b0;
reg    ap_sig_bdd_468;
reg    ap_reg_ppiten_pp5_it1 = 1'b0;
wire   [11:0] p_rec_fu_1233_p2;
reg    ap_sig_cseq_ST_st27_fsm_13;
reg    ap_sig_bdd_509;
reg   [11:0] pix_j_phi_fu_299_p4;
reg   [11:0] pix_j_1_phi_fu_311_p4;
reg   [10:0] pix_i_reg_329;
reg   [11:0] pix_j_3_phi_fu_345_p4;
reg   [10:0] pix_j_4_phi_fu_357_p4;
reg   [10:0] p_12_pn_rec_phi_fu_369_p4;
reg   [10:0] pix_j_5_reg_376;
reg    ap_sig_cseq_ST_st39_fsm_18;
reg    ap_sig_bdd_553;
reg    ap_sig_cseq_ST_st42_fsm_21;
reg    ap_sig_bdd_561;
wire   [63:0] tmp_5_fu_553_p1;
wire   [63:0] tmp_3_fu_674_p1;
wire   [63:0] tmp_10_fu_827_p1;
wire   [63:0] tmp_13_fu_850_p1;
wire   [63:0] tmp_14_fu_861_p1;
wire   [63:0] tmp_15_fu_873_p1;
wire   [63:0] tmp_16_fu_885_p1;
wire   [63:0] tmp_17_fu_905_p1;
wire   [63:0] tmp_30_fu_923_p1;
wire   [63:0] tmp_36_fu_963_p1;
wire   [63:0] tmp_37_fu_976_p1;
wire   [63:0] tmp_40_fu_1198_p1;
wire   [63:0] tmp_42_fu_1211_p1;
wire   [63:0] tmp_41_fu_1222_p1;
wire   [31:0] tmp_35_fu_1168_p5;
reg   [31:0] pixel_fu_140;
wire   [7:0] y_fu_547_p2;
wire   [7:0] y_1_fu_668_p2;
wire   [7:0] y_2_fu_813_p2;
wire   [7:0] in_B_fu_455_p1;
wire   [7:0] grp_fu_417_p4;
wire   [13:0] p_shl1_i_fu_463_p3;
wire   [8:0] p_shl2_i_fu_475_p3;
wire   [14:0] p_shl1_i_cast_fu_471_p1;
wire   [14:0] p_shl2_i_cast_fu_483_p1;
wire   [8:0] tmp_2_i_cast1_fu_487_p1;
wire   [8:0] tmp8_fu_497_p2;
wire   [14:0] p_shl_i_fu_507_p3;
wire   [15:0] p_shl_i_cast_fu_515_p1;
wire   [15:0] tmp20_cast_fu_519_p1;
wire   [15:0] tmp7_fu_522_p2;
wire   [15:0] tmp21_cast_fu_528_p1;
wire   [15:0] tmp_8_i_fu_531_p2;
wire   [7:0] in_B_1_fu_576_p1;
wire   [13:0] p_shl1_i1_fu_584_p3;
wire   [8:0] p_shl2_i1_fu_596_p3;
wire   [14:0] p_shl2_i1_cast_fu_604_p1;
wire   [14:0] p_shl1_i1_cast_fu_592_p1;
wire   [8:0] tmp_2_i1_cast1_fu_608_p1;
wire   [8:0] tmp11_fu_618_p2;
wire   [14:0] p_shl_i1_fu_628_p3;
wire   [15:0] tmp24_cast_fu_640_p1;
wire   [15:0] p_shl_i1_cast_fu_636_p1;
wire   [15:0] tmp25_cast_fu_649_p1;
wire   [15:0] tmp10_fu_643_p2;
wire   [15:0] tmp_8_i1_fu_652_p2;
wire   [0:0] not_tmp_8_fu_690_p2;
wire   [7:0] in_B_2_fu_721_p1;
wire   [13:0] p_shl1_i2_fu_729_p3;
wire   [8:0] p_shl2_i2_fu_741_p3;
wire   [14:0] p_shl1_i2_cast_fu_737_p1;
wire   [14:0] p_shl2_i2_cast_fu_749_p1;
wire   [8:0] tmp_2_i2_cast1_fu_753_p1;
wire   [8:0] tmp16_fu_763_p2;
wire   [14:0] p_shl_i2_fu_773_p3;
wire   [15:0] p_shl_i2_cast_fu_781_p1;
wire   [15:0] tmp28_cast_fu_785_p1;
wire   [15:0] tmp15_fu_788_p2;
wire   [15:0] tmp29_cast_fu_794_p1;
wire   [15:0] tmp_8_i2_fu_797_p2;
wire   [31:0] line_buffer_addr2_fu_819_p3;
wire   [31:0] line_buffer_addr5_fu_866_p3;
wire   [31:0] line_buffer_addr6_fu_878_p3;
wire   [31:0] line_buffer_addr7_fu_898_p3;
wire   [8:0] tmp_20_cast_fu_894_p1;
wire   [8:0] tmp_19_cast_fu_890_p1;
wire   [31:0] line_buffer_addr8_fu_916_p3;
wire   [9:0] tmp_23_fu_936_p3;
wire   [8:0] tmp_18_cast_fu_932_p1;
wire   [8:0] tmp_16_cast_fu_928_p1;
wire   [8:0] tmp_18_fu_947_p2;
wire  signed [10:0] tmp1_cast_fu_943_p1;
wire  signed [10:0] tmp_23_cast_cast_fu_953_p1;
wire   [31:0] line_buffer_addr10_fu_968_p3;
wire   [10:0] tmp_14_cast_fu_987_p1;
wire  signed [10:0] tmp_20_fu_1003_p2;
wire   [10:0] tmp_16_cast1_fu_995_p1;
wire   [8:0] tmp_27_cast_fu_1014_p1;
wire   [8:0] tmp_28_cast_fu_1018_p1;
wire   [9:0] tmp_29_cast_fu_1028_p1;
wire   [9:0] tmp_21_cast_fu_991_p1;
wire   [9:0] tmp_22_fu_1031_p2;
wire   [9:0] tmp_22_cast_fu_999_p1;
wire   [9:0] tmp_38_fu_1043_p3;
wire  signed [10:0] tmp3_cast_fu_1050_p1;
wire  signed [10:0] tmp_31_cast_cast_fu_1054_p1;
wire   [0:0] tmp_25_fu_1063_p2;
wire  signed [10:0] tmp_26_fu_1068_p2;
wire  signed [10:0] tmp_28_fu_1089_p2;
wire   [10:0] y_weight_1_fu_1094_p3;
wire  signed [11:0] x_weight_1_cast_fu_1086_p1;
wire  signed [11:0] y_weight_1_cast_fu_1100_p1;
wire   [0:0] tmp_29_fu_1114_p2;
wire   [7:0] edge_val_fu_1119_p2;
wire   [31:0] tmp_31_fu_1132_p1;
wire   [0:0] tmp_34_fu_1152_p2;
wire   [7:0] p_edge_val_fu_1145_p3;
wire   [7:0] edge_val_2_fu_1156_p3;
wire   [31:0] line_buffer_addr11_fu_1190_p3;
wire   [31:0] line_buffer_addr13_fu_1203_p3;
wire   [5:0] grp_fu_1239_p0;
wire   [7:0] grp_fu_1239_p1;
wire   [8:0] grp_fu_1239_p2;
wire   [5:0] grp_fu_1247_p0;
wire   [7:0] grp_fu_1247_p1;
wire   [8:0] grp_fu_1247_p2;
wire   [5:0] grp_fu_1255_p0;
wire   [7:0] grp_fu_1255_p1;
wire   [8:0] grp_fu_1255_p2;
reg    grp_fu_1239_ce;
reg    grp_fu_1247_ce;
reg    grp_fu_1255_ce;
reg    ap_sig_cseq_ST_st45_fsm_23;
reg    ap_sig_bdd_1217;
reg   [23:0] ap_NS_fsm;
wire   [12:0] grp_fu_1239_p10;
wire   [12:0] grp_fu_1239_p20;
wire   [12:0] grp_fu_1247_p10;
wire   [12:0] grp_fu_1247_p20;
wire   [12:0] grp_fu_1255_p10;
wire   [12:0] grp_fu_1255_p20;


img_process_line_buffer #(
    .DataWidth( 8 ),
    .AddressRange( 6144 ),
    .AddressWidth( 13 ))
line_buffer_U(
    .clk( ap_clk ),
    .reset( ap_rst_n_inv ),
    .address0( line_buffer_address0 ),
    .ce0( line_buffer_ce0 ),
    .we0( line_buffer_we0 ),
    .d0( line_buffer_d0 ),
    .q0( line_buffer_q0 ),
    .address1( line_buffer_address1 ),
    .ce1( line_buffer_ce1 ),
    .we1( line_buffer_we1 ),
    .d1( line_buffer_d1 ),
    .q1( line_buffer_q1 )
);

img_process_mac_muladd_6ns_8ns_9ns_13_3 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 6 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 9 ),
    .dout_WIDTH( 13 ))
img_process_mac_muladd_6ns_8ns_9ns_13_3_U1(
    .clk( ap_clk ),
    .reset( ap_rst_n_inv ),
    .din0( grp_fu_1239_p0 ),
    .din1( grp_fu_1239_p1 ),
    .din2( grp_fu_1239_p2 ),
    .ce( grp_fu_1239_ce ),
    .dout( grp_fu_1239_p3 )
);

img_process_mac_muladd_6ns_8ns_9ns_13_3 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 6 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 9 ),
    .dout_WIDTH( 13 ))
img_process_mac_muladd_6ns_8ns_9ns_13_3_U2(
    .clk( ap_clk ),
    .reset( ap_rst_n_inv ),
    .din0( grp_fu_1247_p0 ),
    .din1( grp_fu_1247_p1 ),
    .din2( grp_fu_1247_p2 ),
    .ce( grp_fu_1247_ce ),
    .dout( grp_fu_1247_p3 )
);

img_process_mac_muladd_6ns_8ns_9ns_13_3 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 6 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 9 ),
    .dout_WIDTH( 13 ))
img_process_mac_muladd_6ns_8ns_9ns_13_3_U3(
    .clk( ap_clk ),
    .reset( ap_rst_n_inv ),
    .din0( grp_fu_1255_p0 ),
    .din1( grp_fu_1255_p1 ),
    .din2( grp_fu_1255_p2 ),
    .ce( grp_fu_1255_ce ),
    .dout( grp_fu_1255_p3 )
);



/// the current state (ap_CS_fsm) of the state machine. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_CS_fsm
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_st1_fsm_0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

/// ap_reg_ppiten_pp0_it0 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it0
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ppiten_pp0_it0 <= ap_const_logic_0;
    end else begin
        if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & ~(ap_const_lv1_0 == exitcond_fu_443_p2))) begin
            ap_reg_ppiten_pp0_it0 <= ap_const_logic_0;
        end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & ~(ap_start == ap_const_logic_0))) begin
            ap_reg_ppiten_pp0_it0 <= ap_const_logic_1;
        end
    end
end

/// ap_reg_ppiten_pp0_it1 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it1
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ppiten_pp0_it1 <= ap_const_logic_0;
    end else begin
        if (((exitcond_reg_1284 == ap_const_lv1_0) & (ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg2_fsm_3))) begin
            ap_reg_ppiten_pp0_it1 <= ap_const_logic_1;
        end else if ((((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & ~(ap_start == ap_const_logic_0)) | ((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg2_fsm_3) & ~(exitcond_reg_1284 == ap_const_lv1_0)))) begin
            ap_reg_ppiten_pp0_it1 <= ap_const_logic_0;
        end
    end
end

/// ap_reg_ppiten_pp0_it2 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it2
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ppiten_pp0_it2 <= ap_const_logic_0;
    end else begin
        if ((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg2_fsm_3)) begin
            ap_reg_ppiten_pp0_it2 <= ap_reg_ppiten_pp0_it1;
        end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & ~(ap_start == ap_const_logic_0))) begin
            ap_reg_ppiten_pp0_it2 <= ap_const_logic_0;
        end
    end
end

/// ap_reg_ppiten_pp1_it0 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp1_it0
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ppiten_pp1_it0 <= ap_const_logic_0;
    end else begin
        if (((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_4) & ~(ap_const_lv1_0 == exitcond1_fu_558_p2))) begin
            ap_reg_ppiten_pp1_it0 <= ap_const_logic_0;
        end else if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~(ap_const_lv1_0 == exitcond_fu_443_p2))) begin
            ap_reg_ppiten_pp1_it0 <= ap_const_logic_1;
        end
    end
end

/// ap_reg_ppiten_pp1_it1 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp1_it1
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ppiten_pp1_it1 <= ap_const_logic_0;
    end else begin
        if (((ap_const_lv1_0 == exitcond1_reg_1313) & (ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg2_fsm_6))) begin
            ap_reg_ppiten_pp1_it1 <= ap_const_logic_1;
        end else if ((((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~(ap_const_lv1_0 == exitcond_fu_443_p2)) | ((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg2_fsm_6) & ~(ap_const_lv1_0 == exitcond1_reg_1313)))) begin
            ap_reg_ppiten_pp1_it1 <= ap_const_logic_0;
        end
    end
end

/// ap_reg_ppiten_pp1_it2 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp1_it2
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ppiten_pp1_it2 <= ap_const_logic_0;
    end else begin
        if ((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg2_fsm_6)) begin
            ap_reg_ppiten_pp1_it2 <= ap_reg_ppiten_pp1_it1;
        end else if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~(ap_const_lv1_0 == exitcond_fu_443_p2))) begin
            ap_reg_ppiten_pp1_it2 <= ap_const_logic_0;
        end
    end
end

/// ap_reg_ppiten_pp2_it0 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp2_it0
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ppiten_pp2_it0 <= ap_const_logic_0;
    end else begin
        if (((ap_const_logic_1 == ap_sig_cseq_ST_pp2_stg0_fsm_7) & ~(ap_sig_bdd_282 & (ap_const_logic_1 == ap_reg_ppiten_pp2_it1)) & ~(ap_const_lv1_0 == exitcond2_fu_678_p2))) begin
            ap_reg_ppiten_pp2_it0 <= ap_const_logic_0;
        end else if (((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_4) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & ~(ap_const_lv1_0 == exitcond1_fu_558_p2))) begin
            ap_reg_ppiten_pp2_it0 <= ap_const_logic_1;
        end
    end
end

/// ap_reg_ppiten_pp2_it1 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp2_it1
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ppiten_pp2_it1 <= ap_const_logic_0;
    end else begin
        if (((ap_const_logic_1 == ap_sig_cseq_ST_pp2_stg0_fsm_7) & ~(ap_sig_bdd_282 & (ap_const_logic_1 == ap_reg_ppiten_pp2_it1)) & (ap_const_lv1_0 == exitcond2_fu_678_p2))) begin
            ap_reg_ppiten_pp2_it1 <= ap_const_logic_1;
        end else if ((((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_4) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & ~(ap_const_lv1_0 == exitcond1_fu_558_p2)) | ((ap_const_logic_1 == ap_sig_cseq_ST_pp2_stg0_fsm_7) & ~(ap_sig_bdd_282 & (ap_const_logic_1 == ap_reg_ppiten_pp2_it1)) & ~(ap_const_lv1_0 == exitcond2_fu_678_p2)))) begin
            ap_reg_ppiten_pp2_it1 <= ap_const_logic_0;
        end
    end
end

/// ap_reg_ppiten_pp3_it0 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp3_it0
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ppiten_pp3_it0 <= ap_const_logic_0;
    end else begin
        if (((ap_const_logic_1 == ap_sig_cseq_ST_pp3_stg0_fsm_10) & ~(ap_const_lv1_0 == exitcond4_fu_709_p2))) begin
            ap_reg_ppiten_pp3_it0 <= ap_const_logic_0;
        end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st19_fsm_9) & (ap_const_lv1_0 == exitcond3_fu_703_p2))) begin
            ap_reg_ppiten_pp3_it0 <= ap_const_logic_1;
        end
    end
end

/// ap_reg_ppiten_pp3_it1 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp3_it1
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ppiten_pp3_it1 <= ap_const_logic_0;
    end else begin
        if (((ap_const_lv1_0 == exitcond4_reg_1365) & (ap_const_logic_1 == ap_sig_cseq_ST_pp3_stg2_fsm_12))) begin
            ap_reg_ppiten_pp3_it1 <= ap_const_logic_1;
        end else if ((((ap_const_logic_1 == ap_sig_cseq_ST_st19_fsm_9) & (ap_const_lv1_0 == exitcond3_fu_703_p2)) | ((ap_const_logic_1 == ap_sig_cseq_ST_pp3_stg2_fsm_12) & ~(ap_const_lv1_0 == exitcond4_reg_1365)))) begin
            ap_reg_ppiten_pp3_it1 <= ap_const_logic_0;
        end
    end
end

/// ap_reg_ppiten_pp3_it2 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp3_it2
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ppiten_pp3_it2 <= ap_const_logic_0;
    end else begin
        if ((ap_const_logic_1 == ap_sig_cseq_ST_pp3_stg2_fsm_12)) begin
            ap_reg_ppiten_pp3_it2 <= ap_reg_ppiten_pp3_it1;
        end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st19_fsm_9) & (ap_const_lv1_0 == exitcond3_fu_703_p2))) begin
            ap_reg_ppiten_pp3_it2 <= ap_const_logic_0;
        end
    end
end

/// ap_reg_ppiten_pp4_it0 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp4_it0
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ppiten_pp4_it0 <= ap_const_logic_0;
    end else begin
        if (((ap_const_logic_1 == ap_sig_cseq_ST_pp4_stg0_fsm_14) & ~(ap_const_lv1_0 == exitcond6_fu_832_p2))) begin
            ap_reg_ppiten_pp4_it0 <= ap_const_logic_0;
        end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st27_fsm_13) & ~(rgb_data_out_full_n == ap_const_logic_0))) begin
            ap_reg_ppiten_pp4_it0 <= ap_const_logic_1;
        end
    end
end

/// ap_reg_ppiten_pp4_it1 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp4_it1
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ppiten_pp4_it1 <= ap_const_logic_0;
    end else begin
        if (((ap_const_lv1_0 == exitcond6_reg_1394) & (ap_const_logic_1 == ap_sig_cseq_ST_pp4_stg3_fsm_17))) begin
            ap_reg_ppiten_pp4_it1 <= ap_const_logic_1;
        end else if ((((ap_const_logic_1 == ap_sig_cseq_ST_st27_fsm_13) & ~(rgb_data_out_full_n == ap_const_logic_0)) | ((ap_const_logic_1 == ap_sig_cseq_ST_pp4_stg3_fsm_17) & ~(ap_const_lv1_0 == exitcond6_reg_1394)))) begin
            ap_reg_ppiten_pp4_it1 <= ap_const_logic_0;
        end
    end
end

/// ap_reg_ppiten_pp4_it2 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp4_it2
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ppiten_pp4_it2 <= ap_const_logic_0;
    end else begin
        if ((ap_const_logic_1 == ap_sig_cseq_ST_pp4_stg3_fsm_17)) begin
            ap_reg_ppiten_pp4_it2 <= ap_reg_ppiten_pp4_it1;
        end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st27_fsm_13) & ~(rgb_data_out_full_n == ap_const_logic_0))) begin
            ap_reg_ppiten_pp4_it2 <= ap_const_logic_0;
        end
    end
end

/// ap_reg_ppiten_pp5_it0 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp5_it0
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ppiten_pp5_it0 <= ap_const_logic_0;
    end else begin
        if (((ap_const_logic_1 == ap_sig_cseq_ST_pp5_stg0_fsm_22) & ~(ap_sig_bdd_468 & (ap_const_logic_1 == ap_reg_ppiten_pp5_it1)) & ~(ap_const_lv1_0 == exitcond8_fu_1227_p2))) begin
            ap_reg_ppiten_pp5_it0 <= ap_const_logic_0;
        end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st19_fsm_9) & ~(ap_const_lv1_0 == exitcond3_fu_703_p2))) begin
            ap_reg_ppiten_pp5_it0 <= ap_const_logic_1;
        end
    end
end

/// ap_reg_ppiten_pp5_it1 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp5_it1
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ppiten_pp5_it1 <= ap_const_logic_0;
    end else begin
        if (((ap_const_logic_1 == ap_sig_cseq_ST_pp5_stg0_fsm_22) & ~(ap_sig_bdd_468 & (ap_const_logic_1 == ap_reg_ppiten_pp5_it1)) & (ap_const_lv1_0 == exitcond8_fu_1227_p2))) begin
            ap_reg_ppiten_pp5_it1 <= ap_const_logic_1;
        end else if ((((ap_const_logic_1 == ap_sig_cseq_ST_st19_fsm_9) & ~(ap_const_lv1_0 == exitcond3_fu_703_p2)) | ((ap_const_logic_1 == ap_sig_cseq_ST_pp5_stg0_fsm_22) & ~(ap_sig_bdd_468 & (ap_const_logic_1 == ap_reg_ppiten_pp5_it1)) & ~(ap_const_lv1_0 == exitcond8_fu_1227_p2)))) begin
            ap_reg_ppiten_pp5_it1 <= ap_const_logic_0;
        end
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_4) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & ~(ap_const_lv1_0 == exitcond1_fu_558_p2))) begin
        p_01_rec_reg_318 <= ap_const_lv12_0;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_pp2_stg0_fsm_7) & (ap_const_logic_1 == ap_reg_ppiten_pp2_it0) & ~(ap_sig_bdd_282 & (ap_const_logic_1 == ap_reg_ppiten_pp2_it1)) & (ap_const_lv1_0 == exitcond2_fu_678_p2))) begin
        p_01_rec_reg_318 <= p_rec3_fu_684_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_reg_ppiten_pp4_it1) & (ap_const_lv1_0 == exitcond6_reg_1394) & (ap_const_logic_1 == ap_sig_cseq_ST_pp4_stg0_fsm_14))) begin
        p_12_pn_rec_reg_365 <= p_23_rec_reg_1398;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st27_fsm_13) & ~(rgb_data_out_full_n == ap_const_logic_0))) begin
        p_12_pn_rec_reg_365 <= ap_const_lv11_0;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st19_fsm_9) & ~(ap_const_lv1_0 == exitcond3_fu_703_p2))) begin
        p_34_rec_reg_388 <= ap_const_lv12_0;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_pp5_stg0_fsm_22) & (ap_const_logic_1 == ap_reg_ppiten_pp5_it0) & ~(ap_sig_bdd_468 & (ap_const_logic_1 == ap_reg_ppiten_pp5_it1)) & (ap_const_lv1_0 == exitcond8_fu_1227_p2))) begin
        p_34_rec_reg_388 <= p_rec_fu_1233_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st18_fsm_8)) begin
        pix_i_reg_329 <= ap_const_lv11_2;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st40_fsm_19) & ~(ap_const_lv1_0 == exitcond5_fu_1178_p2))) begin
        pix_i_reg_329 <= pix_i_1_fu_1216_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~(ap_const_lv1_0 == exitcond_fu_443_p2))) begin
        pix_j_1_reg_307 <= ap_const_lv12_0;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_4) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1) & (ap_const_lv1_0 == exitcond1_reg_1313))) begin
        pix_j_1_reg_307 <= pix_j_6_reg_1317;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st19_fsm_9) & (ap_const_lv1_0 == exitcond3_fu_703_p2))) begin
        pix_j_3_reg_341 <= ap_const_lv12_0;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_pp3_stg0_fsm_10) & (ap_const_logic_1 == ap_reg_ppiten_pp3_it1) & (ap_const_lv1_0 == exitcond4_reg_1365))) begin
        pix_j_3_reg_341 <= pix_j_7_reg_1369;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_reg_ppiten_pp4_it1) & (ap_const_lv1_0 == exitcond6_reg_1394) & (ap_const_logic_1 == ap_sig_cseq_ST_pp4_stg0_fsm_14))) begin
        pix_j_4_reg_353 <= pix_j_9_reg_1414;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st27_fsm_13) & ~(rgb_data_out_full_n == ap_const_logic_0))) begin
        pix_j_4_reg_353 <= ap_const_lv11_1;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st42_fsm_21)) begin
        pix_j_5_reg_376 <= pix_j_8_reg_1541;
    end else if ((~(rgb_data_out_full_n == ap_const_logic_0) & (ap_const_logic_1 == ap_sig_cseq_ST_st39_fsm_18))) begin
        pix_j_5_reg_376 <= ap_const_lv11_0;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & (exitcond_reg_1284 == ap_const_lv1_0))) begin
        pix_j_reg_295 <= pix_j_2_reg_1288;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & ~(ap_start == ap_const_logic_0))) begin
        pix_j_reg_295 <= ap_const_lv12_0;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((((ap_const_lv1_0 == exitcond6_reg_1394) & (ap_const_logic_1 == ap_sig_cseq_ST_pp4_stg3_fsm_17)) | (ap_const_logic_1 == ap_sig_cseq_ST_st41_fsm_20))) begin
        reg_431 <= line_buffer_q1;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_pp4_stg1_fsm_15) & (ap_const_lv1_0 == exitcond6_reg_1394))) begin
        reg_431 <= line_buffer_q0;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((((ap_const_lv1_0 == exitcond6_reg_1394) & (ap_const_logic_1 == ap_sig_cseq_ST_pp4_stg3_fsm_17)) | (ap_const_logic_1 == ap_sig_cseq_ST_st41_fsm_20))) begin
        reg_437 <= line_buffer_q0;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_pp4_stg1_fsm_15) & (ap_const_lv1_0 == exitcond6_reg_1394))) begin
        reg_437 <= line_buffer_q1;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_4)) begin
        ap_reg_ppstg_exitcond1_reg_1313_pp1_it1 <= exitcond1_reg_1313;
        ap_reg_ppstg_line_buffer_addr1_reg_1322_pp1_it1 <= line_buffer_addr1_reg_1322;
        exitcond1_reg_1313 <= exitcond1_fu_558_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_pp3_stg0_fsm_10)) begin
        ap_reg_ppstg_exitcond4_reg_1365_pp3_it1 <= exitcond4_reg_1365;
        ap_reg_ppstg_pix_j_3_reg_341_pp3_it1 <= pix_j_3_reg_341;
        exitcond4_reg_1365 <= exitcond4_fu_709_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_pp4_stg0_fsm_14)) begin
        ap_reg_ppstg_exitcond6_reg_1394_pp4_it1 <= exitcond6_reg_1394;
        ap_reg_ppstg_exitcond6_reg_1394_pp4_it2 <= ap_reg_ppstg_exitcond6_reg_1394_pp4_it1;
        exitcond6_reg_1394 <= exitcond6_fu_832_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_1)) begin
        ap_reg_ppstg_exitcond_reg_1284_pp0_it1 <= exitcond_reg_1284;
        ap_reg_ppstg_pix_j_reg_295_pp0_it1 <= pix_j_reg_295;
        exitcond_reg_1284 <= exitcond_fu_443_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp4_stg3_fsm_17) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond6_reg_1394_pp4_it1))) begin
        edge_val1_reg_1514 <= edge_val1_fu_1124_p3;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp4_stg1_fsm_15) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond6_reg_1394_pp4_it2))) begin
        edge_val_1_reg_1531 <= edge_val_1_fu_1163_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp4_stg2_fsm_16) & ~((ap_const_logic_1 == ap_reg_ppiten_pp4_it2) & ap_sig_bdd_387) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond6_reg_1394_pp4_it1))) begin
        edge_weight_reg_1504 <= edge_weight_fu_1104_p2;
        tmp_39_reg_1509 <= tmp_39_fu_1110_p1;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp2_stg0_fsm_7) & ~(ap_sig_bdd_282 & (ap_const_logic_1 == ap_reg_ppiten_pp2_it1)))) begin
        exitcond2_reg_1347 <= exitcond2_fu_678_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp5_stg0_fsm_22) & ~(ap_sig_bdd_468 & (ap_const_logic_1 == ap_reg_ppiten_pp5_it1)))) begin
        exitcond8_reg_1562 <= exitcond8_fu_1227_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_4) & (ap_const_lv1_0 == exitcond1_fu_558_p2))) begin
        line_buffer_addr1_reg_1322 <= line_buffer_addr1_fu_570_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st40_fsm_19) & (ap_const_lv1_0 == exitcond5_fu_1178_p2))) begin
        line_buffer_addr_11_reg_1546[10 : 0] <= tmp_40_fu_1198_p1[10 : 0];
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_reg_ppiten_pp4_it0) & (ap_const_logic_1 == ap_sig_cseq_ST_pp4_stg0_fsm_14))) begin
        p_23_rec_reg_1398 <= p_23_rec_fu_838_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0))) begin
        pix_j_2_reg_1288 <= pix_j_2_fu_449_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_4) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0))) begin
        pix_j_6_reg_1317 <= pix_j_6_fu_564_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp3_stg0_fsm_10) & (ap_const_logic_1 == ap_reg_ppiten_pp3_it0))) begin
        pix_j_7_reg_1369 <= pix_j_7_fu_715_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st40_fsm_19)) begin
        pix_j_8_reg_1541 <= pix_j_8_fu_1184_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_reg_ppiten_pp4_it0) & (ap_const_logic_1 == ap_sig_cseq_ST_pp4_stg0_fsm_14) & (ap_const_lv1_0 == exitcond6_fu_832_p2))) begin
        pix_j_9_reg_1414 <= pix_j_9_fu_855_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & (exitcond_reg_1284 == ap_const_lv1_0) & (ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg1_fsm_2) & ~((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_214)) | ((ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & (ap_const_lv1_0 == exitcond1_reg_1313) & (ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg1_fsm_5) & ~((ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & ap_sig_bdd_257)) | ((ap_const_logic_1 == ap_reg_ppiten_pp3_it0) & (ap_const_lv1_0 == exitcond4_reg_1365) & (ap_const_logic_1 == ap_sig_cseq_ST_pp3_stg1_fsm_11) & ~((ap_const_logic_1 == ap_reg_ppiten_pp3_it0) & ap_sig_bdd_336)))) begin
        pixel_fu_140 <= rgb_data_in_dout;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (exitcond_reg_1284 == ap_const_lv1_0)) | ((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_4) & (ap_const_lv1_0 == exitcond1_reg_1313)) | ((ap_const_logic_1 == ap_sig_cseq_ST_pp3_stg0_fsm_10) & (ap_const_lv1_0 == exitcond4_reg_1365)))) begin
        reg_427 <= {{pixel_fu_140[ap_const_lv32_F : ap_const_lv32_8]}};
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg1_fsm_5) & ~((ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & ap_sig_bdd_257) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond1_reg_1313_pp1_it1))) begin
        tmp12_reg_1337 <= grp_fu_1247_p3;
        tmp5_reg_1332[14 : 1] <= tmp5_fu_612_p2[14 : 1];
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp3_stg1_fsm_11) & ~((ap_const_logic_1 == ap_reg_ppiten_pp3_it0) & ap_sig_bdd_336) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond4_reg_1365_pp3_it1))) begin
        tmp14_reg_1379[14 : 1] <= tmp14_fu_757_p2[14 : 1];
        tmp17_reg_1384 <= grp_fu_1239_p3;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_lv1_0 == exitcond6_reg_1394) & (ap_const_logic_1 == ap_sig_cseq_ST_pp4_stg0_fsm_14))) begin
        tmp2_reg_1478 <= tmp2_fu_1022_p2;
        tmp_24_reg_1483 <= tmp_24_fu_1037_p2;
        x_weight_reg_1471 <= x_weight_fu_1008_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg1_fsm_2) & ~((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_214) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_1284_pp0_it1))) begin
        tmp6_reg_1298[14 : 1] <= tmp6_fu_491_p2[14 : 1];
        tmp9_reg_1303 <= grp_fu_1255_p3;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp4_stg0_fsm_14) & (ap_const_lv1_0 == exitcond6_fu_832_p2))) begin
        tmp_12_reg_1403 <= tmp_12_fu_844_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_lv1_0 == exitcond6_reg_1394) & (ap_const_logic_1 == ap_sig_cseq_ST_pp4_stg3_fsm_17))) begin
        tmp_19_reg_1451 <= tmp_19_fu_957_p2;
        tmp_21_reg_1466 <= tmp_21_fu_981_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp4_stg1_fsm_15) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond6_reg_1394_pp4_it1))) begin
        tmp_27_reg_1499 <= tmp_27_fu_1080_p2;
        x_weight_1_reg_1494 <= x_weight_1_fu_1073_p3;
        y_weight_reg_1488 <= y_weight_fu_1057_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp4_stg0_fsm_14) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond6_reg_1394_pp4_it1))) begin
        tmp_32_reg_1520 <= tmp_32_fu_1135_p2;
        tmp_33_reg_1526 <= tmp_33_fu_1140_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st18_fsm_8)) begin
        tmp_9_cast_reg_1356 <= tmp_9_cast_fu_695_p3;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg2_fsm_6) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond1_reg_1313_pp1_it1))) begin
        tmp_i1_reg_1342 <= {{tmp_8_i1_fu_652_p2[ap_const_lv32_F : ap_const_lv32_8]}};
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp3_stg2_fsm_12) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond4_reg_1365_pp3_it1))) begin
        tmp_i2_reg_1389 <= {{tmp_8_i2_fu_797_p2[ap_const_lv32_F : ap_const_lv32_8]}};
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg2_fsm_3) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_1284_pp0_it1))) begin
        tmp_i_reg_1308 <= {{tmp_8_i_fu_531_p2[ap_const_lv32_F : ap_const_lv32_8]}};
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_lv1_0 == exitcond6_reg_1394) & (ap_const_logic_1 == ap_sig_cseq_ST_pp4_stg2_fsm_16) & ~((ap_const_logic_1 == ap_reg_ppiten_pp4_it2) & ap_sig_bdd_387))) begin
        tmp_reg_1441 <= tmp_fu_910_p2;
    end
end

/// ap_done assign process. ///
always @ (ap_sig_cseq_ST_st45_fsm_23)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st45_fsm_23)) begin
        ap_done = ap_const_logic_1;
    end else begin
        ap_done = ap_const_logic_0;
    end
end

/// ap_idle assign process. ///
always @ (ap_start or ap_sig_cseq_ST_st1_fsm_0)
begin
    if ((~(ap_const_logic_1 == ap_start) & (ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0))) begin
        ap_idle = ap_const_logic_1;
    end else begin
        ap_idle = ap_const_logic_0;
    end
end

/// ap_ready assign process. ///
always @ (ap_sig_cseq_ST_st45_fsm_23)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st45_fsm_23)) begin
        ap_ready = ap_const_logic_1;
    end else begin
        ap_ready = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_pp0_stg0_fsm_1 assign process. ///
always @ (ap_sig_bdd_83)
begin
    if (ap_sig_bdd_83) begin
        ap_sig_cseq_ST_pp0_stg0_fsm_1 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_pp0_stg0_fsm_1 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_pp0_stg1_fsm_2 assign process. ///
always @ (ap_sig_bdd_210)
begin
    if (ap_sig_bdd_210) begin
        ap_sig_cseq_ST_pp0_stg1_fsm_2 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_pp0_stg1_fsm_2 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_pp0_stg2_fsm_3 assign process. ///
always @ (ap_sig_bdd_200)
begin
    if (ap_sig_bdd_200) begin
        ap_sig_cseq_ST_pp0_stg2_fsm_3 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_pp0_stg2_fsm_3 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_pp1_stg0_fsm_4 assign process. ///
always @ (ap_sig_bdd_128)
begin
    if (ap_sig_bdd_128) begin
        ap_sig_cseq_ST_pp1_stg0_fsm_4 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_pp1_stg0_fsm_4 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_pp1_stg1_fsm_5 assign process. ///
always @ (ap_sig_bdd_254)
begin
    if (ap_sig_bdd_254) begin
        ap_sig_cseq_ST_pp1_stg1_fsm_5 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_pp1_stg1_fsm_5 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_pp1_stg2_fsm_6 assign process. ///
always @ (ap_sig_bdd_244)
begin
    if (ap_sig_bdd_244) begin
        ap_sig_cseq_ST_pp1_stg2_fsm_6 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_pp1_stg2_fsm_6 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_pp2_stg0_fsm_7 assign process. ///
always @ (ap_sig_bdd_275)
begin
    if (ap_sig_bdd_275) begin
        ap_sig_cseq_ST_pp2_stg0_fsm_7 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_pp2_stg0_fsm_7 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_pp3_stg0_fsm_10 assign process. ///
always @ (ap_sig_bdd_103)
begin
    if (ap_sig_bdd_103) begin
        ap_sig_cseq_ST_pp3_stg0_fsm_10 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_pp3_stg0_fsm_10 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_pp3_stg1_fsm_11 assign process. ///
always @ (ap_sig_bdd_333)
begin
    if (ap_sig_bdd_333) begin
        ap_sig_cseq_ST_pp3_stg1_fsm_11 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_pp3_stg1_fsm_11 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_pp3_stg2_fsm_12 assign process. ///
always @ (ap_sig_bdd_323)
begin
    if (ap_sig_bdd_323) begin
        ap_sig_cseq_ST_pp3_stg2_fsm_12 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_pp3_stg2_fsm_12 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_pp4_stg0_fsm_14 assign process. ///
always @ (ap_sig_bdd_353)
begin
    if (ap_sig_bdd_353) begin
        ap_sig_cseq_ST_pp4_stg0_fsm_14 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_pp4_stg0_fsm_14 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_pp4_stg1_fsm_15 assign process. ///
always @ (ap_sig_bdd_150)
begin
    if (ap_sig_bdd_150) begin
        ap_sig_cseq_ST_pp4_stg1_fsm_15 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_pp4_stg1_fsm_15 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_pp4_stg2_fsm_16 assign process. ///
always @ (ap_sig_bdd_383)
begin
    if (ap_sig_bdd_383) begin
        ap_sig_cseq_ST_pp4_stg2_fsm_16 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_pp4_stg2_fsm_16 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_pp4_stg3_fsm_17 assign process. ///
always @ (ap_sig_bdd_166)
begin
    if (ap_sig_bdd_166) begin
        ap_sig_cseq_ST_pp4_stg3_fsm_17 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_pp4_stg3_fsm_17 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_pp5_stg0_fsm_22 assign process. ///
always @ (ap_sig_bdd_462)
begin
    if (ap_sig_bdd_462) begin
        ap_sig_cseq_ST_pp5_stg0_fsm_22 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_pp5_stg0_fsm_22 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st18_fsm_8 assign process. ///
always @ (ap_sig_bdd_299)
begin
    if (ap_sig_bdd_299) begin
        ap_sig_cseq_ST_st18_fsm_8 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st18_fsm_8 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st19_fsm_9 assign process. ///
always @ (ap_sig_bdd_308)
begin
    if (ap_sig_bdd_308) begin
        ap_sig_cseq_ST_st19_fsm_9 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st19_fsm_9 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st1_fsm_0 assign process. ///
always @ (ap_sig_bdd_42)
begin
    if (ap_sig_bdd_42) begin
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st27_fsm_13 assign process. ///
always @ (ap_sig_bdd_509)
begin
    if (ap_sig_bdd_509) begin
        ap_sig_cseq_ST_st27_fsm_13 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st27_fsm_13 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st39_fsm_18 assign process. ///
always @ (ap_sig_bdd_553)
begin
    if (ap_sig_bdd_553) begin
        ap_sig_cseq_ST_st39_fsm_18 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st39_fsm_18 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st40_fsm_19 assign process. ///
always @ (ap_sig_bdd_442)
begin
    if (ap_sig_bdd_442) begin
        ap_sig_cseq_ST_st40_fsm_19 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st40_fsm_19 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st41_fsm_20 assign process. ///
always @ (ap_sig_bdd_174)
begin
    if (ap_sig_bdd_174) begin
        ap_sig_cseq_ST_st41_fsm_20 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st41_fsm_20 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st42_fsm_21 assign process. ///
always @ (ap_sig_bdd_561)
begin
    if (ap_sig_bdd_561) begin
        ap_sig_cseq_ST_st42_fsm_21 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st42_fsm_21 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st45_fsm_23 assign process. ///
always @ (ap_sig_bdd_1217)
begin
    if (ap_sig_bdd_1217) begin
        ap_sig_cseq_ST_st45_fsm_23 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st45_fsm_23 = ap_const_logic_0;
    end
end

/// grp_fu_1239_ce assign process. ///
always @ (ap_sig_cseq_ST_pp3_stg0_fsm_10 or ap_reg_ppiten_pp3_it0 or ap_sig_cseq_ST_pp3_stg2_fsm_12 or ap_sig_cseq_ST_pp3_stg1_fsm_11 or ap_sig_bdd_336)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp3_stg0_fsm_10) | (ap_const_logic_1 == ap_sig_cseq_ST_pp3_stg2_fsm_12) | ((ap_const_logic_1 == ap_sig_cseq_ST_pp3_stg1_fsm_11) & ~((ap_const_logic_1 == ap_reg_ppiten_pp3_it0) & ap_sig_bdd_336)))) begin
        grp_fu_1239_ce = ap_const_logic_1;
    end else begin
        grp_fu_1239_ce = ap_const_logic_0;
    end
end

/// grp_fu_1247_ce assign process. ///
always @ (ap_sig_cseq_ST_pp1_stg0_fsm_4 or ap_reg_ppiten_pp1_it0 or ap_sig_cseq_ST_pp1_stg2_fsm_6 or ap_sig_cseq_ST_pp1_stg1_fsm_5 or ap_sig_bdd_257)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_4) | (ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg2_fsm_6) | ((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg1_fsm_5) & ~((ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & ap_sig_bdd_257)))) begin
        grp_fu_1247_ce = ap_const_logic_1;
    end else begin
        grp_fu_1247_ce = ap_const_logic_0;
    end
end

/// grp_fu_1255_ce assign process. ///
always @ (ap_sig_cseq_ST_pp0_stg0_fsm_1 or ap_reg_ppiten_pp0_it0 or ap_sig_cseq_ST_pp0_stg2_fsm_3 or ap_sig_cseq_ST_pp0_stg1_fsm_2 or ap_sig_bdd_214)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) | (ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg2_fsm_3) | ((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg1_fsm_2) & ~((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_214)))) begin
        grp_fu_1255_ce = ap_const_logic_1;
    end else begin
        grp_fu_1255_ce = ap_const_logic_0;
    end
end

/// line_buffer_address0 assign process. ///
always @ (ap_sig_cseq_ST_pp0_stg0_fsm_1 or ap_reg_ppiten_pp0_it2 or ap_sig_cseq_ST_pp3_stg0_fsm_10 or ap_reg_ppiten_pp3_it2 or ap_sig_cseq_ST_pp1_stg0_fsm_4 or ap_reg_ppiten_pp1_it2 or ap_sig_cseq_ST_pp4_stg1_fsm_15 or ap_reg_ppiten_pp4_it0 or ap_sig_cseq_ST_pp4_stg3_fsm_17 or ap_sig_cseq_ST_pp4_stg0_fsm_14 or ap_sig_cseq_ST_pp4_stg2_fsm_16 or ap_sig_cseq_ST_st40_fsm_19 or line_buffer_addr_11_reg_1546 or ap_sig_cseq_ST_st42_fsm_21 or tmp_5_fu_553_p1 or tmp_3_fu_674_p1 or tmp_10_fu_827_p1 or tmp_13_fu_850_p1 or tmp_16_fu_885_p1 or tmp_30_fu_923_p1 or tmp_37_fu_976_p1 or tmp_42_fu_1211_p1)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st42_fsm_21)) begin
        line_buffer_address0 = line_buffer_addr_11_reg_1546;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_pp3_stg0_fsm_10) & (ap_const_logic_1 == ap_reg_ppiten_pp3_it2))) begin
        line_buffer_address0 = tmp_10_fu_827_p1;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_4) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it2))) begin
        line_buffer_address0 = tmp_3_fu_674_p1;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2))) begin
        line_buffer_address0 = tmp_5_fu_553_p1;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st40_fsm_19)) begin
        line_buffer_address0 = tmp_42_fu_1211_p1;
    end else if (((ap_const_logic_1 == ap_reg_ppiten_pp4_it0) & (ap_const_logic_1 == ap_sig_cseq_ST_pp4_stg3_fsm_17))) begin
        line_buffer_address0 = tmp_37_fu_976_p1;
    end else if (((ap_const_logic_1 == ap_reg_ppiten_pp4_it0) & (ap_const_logic_1 == ap_sig_cseq_ST_pp4_stg2_fsm_16))) begin
        line_buffer_address0 = tmp_30_fu_923_p1;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_pp4_stg1_fsm_15) & (ap_const_logic_1 == ap_reg_ppiten_pp4_it0))) begin
        line_buffer_address0 = tmp_16_fu_885_p1;
    end else if (((ap_const_logic_1 == ap_reg_ppiten_pp4_it0) & (ap_const_logic_1 == ap_sig_cseq_ST_pp4_stg0_fsm_14))) begin
        line_buffer_address0 = tmp_13_fu_850_p1;
    end else begin
        line_buffer_address0 = 'bx;
    end
end

/// line_buffer_address1 assign process. ///
always @ (ap_sig_cseq_ST_pp4_stg1_fsm_15 or ap_reg_ppiten_pp4_it0 or ap_sig_cseq_ST_pp4_stg3_fsm_17 or ap_sig_cseq_ST_pp4_stg0_fsm_14 or ap_sig_cseq_ST_pp4_stg2_fsm_16 or ap_sig_cseq_ST_st40_fsm_19 or ap_sig_cseq_ST_st42_fsm_21 or tmp_14_fu_861_p1 or tmp_15_fu_873_p1 or tmp_17_fu_905_p1 or tmp_36_fu_963_p1 or tmp_40_fu_1198_p1 or tmp_41_fu_1222_p1)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st42_fsm_21)) begin
        line_buffer_address1 = tmp_41_fu_1222_p1;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st40_fsm_19)) begin
        line_buffer_address1 = tmp_40_fu_1198_p1;
    end else if (((ap_const_logic_1 == ap_reg_ppiten_pp4_it0) & (ap_const_logic_1 == ap_sig_cseq_ST_pp4_stg3_fsm_17))) begin
        line_buffer_address1 = tmp_36_fu_963_p1;
    end else if (((ap_const_logic_1 == ap_reg_ppiten_pp4_it0) & (ap_const_logic_1 == ap_sig_cseq_ST_pp4_stg2_fsm_16))) begin
        line_buffer_address1 = tmp_17_fu_905_p1;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_pp4_stg1_fsm_15) & (ap_const_logic_1 == ap_reg_ppiten_pp4_it0))) begin
        line_buffer_address1 = tmp_15_fu_873_p1;
    end else if (((ap_const_logic_1 == ap_reg_ppiten_pp4_it0) & (ap_const_logic_1 == ap_sig_cseq_ST_pp4_stg0_fsm_14))) begin
        line_buffer_address1 = tmp_14_fu_861_p1;
    end else begin
        line_buffer_address1 = 'bx;
    end
end

/// line_buffer_ce0 assign process. ///
always @ (ap_sig_cseq_ST_pp0_stg0_fsm_1 or ap_reg_ppiten_pp0_it2 or ap_sig_cseq_ST_pp3_stg0_fsm_10 or ap_reg_ppiten_pp3_it2 or ap_sig_cseq_ST_pp1_stg0_fsm_4 or ap_reg_ppiten_pp1_it2 or ap_sig_cseq_ST_pp4_stg1_fsm_15 or ap_reg_ppiten_pp4_it0 or ap_reg_ppiten_pp4_it2 or ap_sig_cseq_ST_pp4_stg3_fsm_17 or ap_sig_cseq_ST_pp4_stg0_fsm_14 or ap_sig_cseq_ST_pp4_stg2_fsm_16 or ap_sig_bdd_387 or ap_sig_cseq_ST_st40_fsm_19 or ap_sig_cseq_ST_st42_fsm_21)
begin
    if ((((ap_const_logic_1 == ap_reg_ppiten_pp4_it0) & (ap_const_logic_1 == ap_sig_cseq_ST_pp4_stg0_fsm_14)) | (ap_const_logic_1 == ap_sig_cseq_ST_st40_fsm_19) | (ap_const_logic_1 == ap_sig_cseq_ST_st42_fsm_21) | ((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | ((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_4) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it2)) | ((ap_const_logic_1 == ap_sig_cseq_ST_pp3_stg0_fsm_10) & (ap_const_logic_1 == ap_reg_ppiten_pp3_it2)) | ((ap_const_logic_1 == ap_sig_cseq_ST_pp4_stg1_fsm_15) & (ap_const_logic_1 == ap_reg_ppiten_pp4_it0)) | ((ap_const_logic_1 == ap_reg_ppiten_pp4_it0) & (ap_const_logic_1 == ap_sig_cseq_ST_pp4_stg3_fsm_17)) | ((ap_const_logic_1 == ap_reg_ppiten_pp4_it0) & (ap_const_logic_1 == ap_sig_cseq_ST_pp4_stg2_fsm_16) & ~((ap_const_logic_1 == ap_reg_ppiten_pp4_it2) & ap_sig_bdd_387)))) begin
        line_buffer_ce0 = ap_const_logic_1;
    end else begin
        line_buffer_ce0 = ap_const_logic_0;
    end
end

/// line_buffer_ce1 assign process. ///
always @ (ap_sig_cseq_ST_pp4_stg1_fsm_15 or ap_reg_ppiten_pp4_it0 or ap_reg_ppiten_pp4_it2 or ap_sig_cseq_ST_pp4_stg3_fsm_17 or ap_sig_cseq_ST_pp4_stg0_fsm_14 or ap_sig_cseq_ST_pp4_stg2_fsm_16 or ap_sig_bdd_387 or ap_sig_cseq_ST_st40_fsm_19 or ap_sig_cseq_ST_st42_fsm_21)
begin
    if ((((ap_const_logic_1 == ap_reg_ppiten_pp4_it0) & (ap_const_logic_1 == ap_sig_cseq_ST_pp4_stg0_fsm_14)) | (ap_const_logic_1 == ap_sig_cseq_ST_st40_fsm_19) | (ap_const_logic_1 == ap_sig_cseq_ST_st42_fsm_21) | ((ap_const_logic_1 == ap_sig_cseq_ST_pp4_stg1_fsm_15) & (ap_const_logic_1 == ap_reg_ppiten_pp4_it0)) | ((ap_const_logic_1 == ap_reg_ppiten_pp4_it0) & (ap_const_logic_1 == ap_sig_cseq_ST_pp4_stg3_fsm_17)) | ((ap_const_logic_1 == ap_reg_ppiten_pp4_it0) & (ap_const_logic_1 == ap_sig_cseq_ST_pp4_stg2_fsm_16) & ~((ap_const_logic_1 == ap_reg_ppiten_pp4_it2) & ap_sig_bdd_387)))) begin
        line_buffer_ce1 = ap_const_logic_1;
    end else begin
        line_buffer_ce1 = ap_const_logic_0;
    end
end

/// line_buffer_d0 assign process. ///
always @ (ap_sig_cseq_ST_pp0_stg0_fsm_1 or ap_reg_ppiten_pp0_it2 or ap_sig_cseq_ST_pp3_stg0_fsm_10 or ap_reg_ppiten_pp3_it2 or ap_sig_cseq_ST_pp1_stg0_fsm_4 or ap_reg_ppiten_pp1_it2 or reg_437 or ap_sig_cseq_ST_st42_fsm_21 or y_fu_547_p2 or y_1_fu_668_p2 or y_2_fu_813_p2)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st42_fsm_21)) begin
        line_buffer_d0 = reg_437;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_pp3_stg0_fsm_10) & (ap_const_logic_1 == ap_reg_ppiten_pp3_it2))) begin
        line_buffer_d0 = y_2_fu_813_p2;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_4) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it2))) begin
        line_buffer_d0 = y_1_fu_668_p2;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2))) begin
        line_buffer_d0 = y_fu_547_p2;
    end else begin
        line_buffer_d0 = 'bx;
    end
end

/// line_buffer_we0 assign process. ///
always @ (ap_sig_cseq_ST_pp0_stg0_fsm_1 or ap_reg_ppiten_pp0_it2 or ap_sig_cseq_ST_pp3_stg0_fsm_10 or ap_reg_ppiten_pp3_it2 or ap_sig_cseq_ST_pp1_stg0_fsm_4 or ap_reg_ppiten_pp1_it2 or ap_reg_ppstg_exitcond_reg_1284_pp0_it1 or ap_reg_ppstg_exitcond1_reg_1313_pp1_it1 or ap_reg_ppstg_exitcond4_reg_1365_pp3_it1 or ap_sig_cseq_ST_st42_fsm_21)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st42_fsm_21) | ((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_1284_pp0_it1)) | ((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_4) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it2) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond1_reg_1313_pp1_it1)) | ((ap_const_logic_1 == ap_sig_cseq_ST_pp3_stg0_fsm_10) & (ap_const_logic_1 == ap_reg_ppiten_pp3_it2) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond4_reg_1365_pp3_it1)))) begin
        line_buffer_we0 = ap_const_logic_1;
    end else begin
        line_buffer_we0 = ap_const_logic_0;
    end
end

/// line_buffer_we1 assign process. ///
always @ (ap_sig_cseq_ST_st42_fsm_21)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st42_fsm_21)) begin
        line_buffer_we1 = ap_const_logic_1;
    end else begin
        line_buffer_we1 = ap_const_logic_0;
    end
end

/// p_12_pn_rec_phi_fu_369_p4 assign process. ///
always @ (p_12_pn_rec_reg_365 or ap_reg_ppiten_pp4_it1 or exitcond6_reg_1394 or ap_sig_cseq_ST_pp4_stg0_fsm_14 or p_23_rec_reg_1398)
begin
    if (((ap_const_logic_1 == ap_reg_ppiten_pp4_it1) & (ap_const_lv1_0 == exitcond6_reg_1394) & (ap_const_logic_1 == ap_sig_cseq_ST_pp4_stg0_fsm_14))) begin
        p_12_pn_rec_phi_fu_369_p4 = p_23_rec_reg_1398;
    end else begin
        p_12_pn_rec_phi_fu_369_p4 = p_12_pn_rec_reg_365;
    end
end

/// pix_j_1_phi_fu_311_p4 assign process. ///
always @ (pix_j_1_reg_307 or ap_sig_cseq_ST_pp1_stg0_fsm_4 or ap_reg_ppiten_pp1_it1 or exitcond1_reg_1313 or pix_j_6_reg_1317)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_4) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1) & (ap_const_lv1_0 == exitcond1_reg_1313))) begin
        pix_j_1_phi_fu_311_p4 = pix_j_6_reg_1317;
    end else begin
        pix_j_1_phi_fu_311_p4 = pix_j_1_reg_307;
    end
end

/// pix_j_3_phi_fu_345_p4 assign process. ///
always @ (pix_j_3_reg_341 or ap_sig_cseq_ST_pp3_stg0_fsm_10 or ap_reg_ppiten_pp3_it1 or exitcond4_reg_1365 or pix_j_7_reg_1369)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp3_stg0_fsm_10) & (ap_const_logic_1 == ap_reg_ppiten_pp3_it1) & (ap_const_lv1_0 == exitcond4_reg_1365))) begin
        pix_j_3_phi_fu_345_p4 = pix_j_7_reg_1369;
    end else begin
        pix_j_3_phi_fu_345_p4 = pix_j_3_reg_341;
    end
end

/// pix_j_4_phi_fu_357_p4 assign process. ///
always @ (pix_j_4_reg_353 or ap_reg_ppiten_pp4_it1 or exitcond6_reg_1394 or ap_sig_cseq_ST_pp4_stg0_fsm_14 or pix_j_9_reg_1414)
begin
    if (((ap_const_logic_1 == ap_reg_ppiten_pp4_it1) & (ap_const_lv1_0 == exitcond6_reg_1394) & (ap_const_logic_1 == ap_sig_cseq_ST_pp4_stg0_fsm_14))) begin
        pix_j_4_phi_fu_357_p4 = pix_j_9_reg_1414;
    end else begin
        pix_j_4_phi_fu_357_p4 = pix_j_4_reg_353;
    end
end

/// pix_j_phi_fu_299_p4 assign process. ///
always @ (pix_j_reg_295 or ap_sig_cseq_ST_pp0_stg0_fsm_1 or ap_reg_ppiten_pp0_it1 or exitcond_reg_1284 or pix_j_2_reg_1288)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & (exitcond_reg_1284 == ap_const_lv1_0))) begin
        pix_j_phi_fu_299_p4 = pix_j_2_reg_1288;
    end else begin
        pix_j_phi_fu_299_p4 = pix_j_reg_295;
    end
end

/// rgb_data_in_read assign process. ///
always @ (ap_reg_ppiten_pp0_it0 or ap_reg_ppiten_pp3_it0 or exitcond_reg_1284 or ap_reg_ppiten_pp1_it0 or exitcond1_reg_1313 or exitcond4_reg_1365 or ap_sig_cseq_ST_pp0_stg1_fsm_2 or ap_sig_bdd_214 or ap_sig_cseq_ST_pp1_stg1_fsm_5 or ap_sig_bdd_257 or ap_sig_cseq_ST_pp3_stg1_fsm_11 or ap_sig_bdd_336)
begin
    if ((((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & (exitcond_reg_1284 == ap_const_lv1_0) & (ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg1_fsm_2) & ~((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_214)) | ((ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & (ap_const_lv1_0 == exitcond1_reg_1313) & (ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg1_fsm_5) & ~((ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & ap_sig_bdd_257)) | ((ap_const_logic_1 == ap_reg_ppiten_pp3_it0) & (ap_const_lv1_0 == exitcond4_reg_1365) & (ap_const_logic_1 == ap_sig_cseq_ST_pp3_stg1_fsm_11) & ~((ap_const_logic_1 == ap_reg_ppiten_pp3_it0) & ap_sig_bdd_336)))) begin
        rgb_data_in_read = ap_const_logic_1;
    end else begin
        rgb_data_in_read = ap_const_logic_0;
    end
end

/// rgb_data_out_din assign process. ///
always @ (rgb_data_out_full_n or ap_reg_ppiten_pp4_it2 or exitcond2_reg_1347 or ap_sig_cseq_ST_pp2_stg0_fsm_7 or ap_sig_bdd_282 or ap_reg_ppiten_pp2_it1 or ap_reg_ppstg_exitcond6_reg_1394_pp4_it2 or ap_sig_cseq_ST_pp4_stg2_fsm_16 or ap_sig_bdd_387 or exitcond8_reg_1562 or ap_sig_cseq_ST_pp5_stg0_fsm_22 or ap_sig_bdd_468 or ap_reg_ppiten_pp5_it1 or ap_sig_cseq_ST_st27_fsm_13 or ap_sig_cseq_ST_st39_fsm_18 or tmp_35_fu_1168_p5)
begin
    if (((ap_const_logic_1 == ap_reg_ppiten_pp4_it2) & (ap_const_logic_1 == ap_sig_cseq_ST_pp4_stg2_fsm_16) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond6_reg_1394_pp4_it2) & ~((ap_const_logic_1 == ap_reg_ppiten_pp4_it2) & ap_sig_bdd_387))) begin
        rgb_data_out_din = tmp_35_fu_1168_p5;
    end else if ((((ap_const_logic_1 == ap_sig_cseq_ST_st27_fsm_13) & ~(rgb_data_out_full_n == ap_const_logic_0)) | (~(rgb_data_out_full_n == ap_const_logic_0) & (ap_const_logic_1 == ap_sig_cseq_ST_st39_fsm_18)) | ((ap_const_logic_1 == ap_sig_cseq_ST_pp2_stg0_fsm_7) & (ap_const_lv1_0 == exitcond2_reg_1347) & (ap_const_logic_1 == ap_reg_ppiten_pp2_it1) & ~(ap_sig_bdd_282 & (ap_const_logic_1 == ap_reg_ppiten_pp2_it1))) | ((ap_const_logic_1 == ap_sig_cseq_ST_pp5_stg0_fsm_22) & (ap_const_lv1_0 == exitcond8_reg_1562) & (ap_const_logic_1 == ap_reg_ppiten_pp5_it1) & ~(ap_sig_bdd_468 & (ap_const_logic_1 == ap_reg_ppiten_pp5_it1))))) begin
        rgb_data_out_din = ap_const_lv32_0;
    end else begin
        rgb_data_out_din = 'bx;
    end
end

/// rgb_data_out_write assign process. ///
always @ (rgb_data_out_full_n or ap_reg_ppiten_pp4_it2 or exitcond2_reg_1347 or ap_sig_cseq_ST_pp2_stg0_fsm_7 or ap_sig_bdd_282 or ap_reg_ppiten_pp2_it1 or ap_reg_ppstg_exitcond6_reg_1394_pp4_it2 or ap_sig_cseq_ST_pp4_stg2_fsm_16 or ap_sig_bdd_387 or exitcond8_reg_1562 or ap_sig_cseq_ST_pp5_stg0_fsm_22 or ap_sig_bdd_468 or ap_reg_ppiten_pp5_it1 or ap_sig_cseq_ST_st27_fsm_13 or ap_sig_cseq_ST_st39_fsm_18)
begin
    if ((((ap_const_logic_1 == ap_sig_cseq_ST_st27_fsm_13) & ~(rgb_data_out_full_n == ap_const_logic_0)) | (~(rgb_data_out_full_n == ap_const_logic_0) & (ap_const_logic_1 == ap_sig_cseq_ST_st39_fsm_18)) | ((ap_const_logic_1 == ap_sig_cseq_ST_pp2_stg0_fsm_7) & (ap_const_lv1_0 == exitcond2_reg_1347) & (ap_const_logic_1 == ap_reg_ppiten_pp2_it1) & ~(ap_sig_bdd_282 & (ap_const_logic_1 == ap_reg_ppiten_pp2_it1))) | ((ap_const_logic_1 == ap_reg_ppiten_pp4_it2) & (ap_const_logic_1 == ap_sig_cseq_ST_pp4_stg2_fsm_16) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond6_reg_1394_pp4_it2) & ~((ap_const_logic_1 == ap_reg_ppiten_pp4_it2) & ap_sig_bdd_387)) | ((ap_const_logic_1 == ap_sig_cseq_ST_pp5_stg0_fsm_22) & (ap_const_lv1_0 == exitcond8_reg_1562) & (ap_const_logic_1 == ap_reg_ppiten_pp5_it1) & ~(ap_sig_bdd_468 & (ap_const_logic_1 == ap_reg_ppiten_pp5_it1))))) begin
        rgb_data_out_write = ap_const_logic_1;
    end else begin
        rgb_data_out_write = ap_const_logic_0;
    end
end
/// the next state (ap_NS_fsm) of the state machine. ///
always @ (ap_start or ap_CS_fsm or rgb_data_out_full_n or ap_sig_cseq_ST_pp0_stg0_fsm_1 or ap_reg_ppiten_pp0_it0 or ap_reg_ppiten_pp0_it1 or ap_reg_ppiten_pp0_it2 or ap_sig_cseq_ST_pp3_stg0_fsm_10 or ap_reg_ppiten_pp3_it0 or ap_reg_ppiten_pp3_it1 or ap_reg_ppiten_pp3_it2 or ap_sig_cseq_ST_pp1_stg0_fsm_4 or ap_reg_ppiten_pp1_it0 or ap_reg_ppiten_pp1_it1 or ap_reg_ppiten_pp1_it2 or ap_reg_ppiten_pp4_it0 or ap_reg_ppiten_pp4_it1 or ap_reg_ppiten_pp4_it2 or exitcond_fu_443_p2 or ap_sig_bdd_214 or exitcond1_fu_558_p2 or ap_sig_bdd_257 or exitcond2_fu_678_p2 or ap_reg_ppiten_pp2_it0 or ap_sig_bdd_282 or ap_reg_ppiten_pp2_it1 or exitcond3_fu_703_p2 or exitcond4_fu_709_p2 or ap_sig_bdd_336 or exitcond6_fu_832_p2 or ap_sig_cseq_ST_pp4_stg2_fsm_16 or ap_sig_bdd_387 or exitcond5_fu_1178_p2 or exitcond8_fu_1227_p2 or ap_reg_ppiten_pp5_it0 or ap_sig_bdd_468 or ap_reg_ppiten_pp5_it1)
begin
    case (ap_CS_fsm)
        ap_ST_st1_fsm_0 : 
        begin
            if (~(ap_start == ap_const_logic_0)) begin
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_1;
            end else begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end
        end
        ap_ST_pp0_stg0_fsm_1 : 
        begin
            if ((~((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) & ~((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~(ap_const_lv1_0 == exitcond_fu_443_p2) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it1)))) begin
                ap_NS_fsm = ap_ST_pp0_stg1_fsm_2;
            end else if (((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~(ap_const_lv1_0 == exitcond_fu_443_p2) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it1))) begin
                ap_NS_fsm = ap_ST_pp1_stg0_fsm_4;
            end else begin
                ap_NS_fsm = ap_ST_pp1_stg0_fsm_4;
            end
        end
        ap_ST_pp0_stg1_fsm_2 : 
        begin
            if (~((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ap_sig_bdd_214)) begin
                ap_NS_fsm = ap_ST_pp0_stg2_fsm_3;
            end else begin
                ap_NS_fsm = ap_ST_pp0_stg1_fsm_2;
            end
        end
        ap_ST_pp0_stg2_fsm_3 : 
        begin
            ap_NS_fsm = ap_ST_pp0_stg0_fsm_1;
        end
        ap_ST_pp1_stg0_fsm_4 : 
        begin
            if ((~((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_4) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it2) & ~(ap_const_logic_1 == ap_reg_ppiten_pp1_it1)) & ~((ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & ~(ap_const_lv1_0 == exitcond1_fu_558_p2) & ~(ap_const_logic_1 == ap_reg_ppiten_pp1_it1)))) begin
                ap_NS_fsm = ap_ST_pp1_stg1_fsm_5;
            end else if (((ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & ~(ap_const_lv1_0 == exitcond1_fu_558_p2) & ~(ap_const_logic_1 == ap_reg_ppiten_pp1_it1))) begin
                ap_NS_fsm = ap_ST_pp2_stg0_fsm_7;
            end else begin
                ap_NS_fsm = ap_ST_pp2_stg0_fsm_7;
            end
        end
        ap_ST_pp1_stg1_fsm_5 : 
        begin
            if (~((ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & ap_sig_bdd_257)) begin
                ap_NS_fsm = ap_ST_pp1_stg2_fsm_6;
            end else begin
                ap_NS_fsm = ap_ST_pp1_stg1_fsm_5;
            end
        end
        ap_ST_pp1_stg2_fsm_6 : 
        begin
            ap_NS_fsm = ap_ST_pp1_stg0_fsm_4;
        end
        ap_ST_pp2_stg0_fsm_7 : 
        begin
            if (~((ap_const_logic_1 == ap_reg_ppiten_pp2_it0) & ~(ap_sig_bdd_282 & (ap_const_logic_1 == ap_reg_ppiten_pp2_it1)) & ~(ap_const_lv1_0 == exitcond2_fu_678_p2))) begin
                ap_NS_fsm = ap_ST_pp2_stg0_fsm_7;
            end else if (((ap_const_logic_1 == ap_reg_ppiten_pp2_it0) & ~(ap_sig_bdd_282 & (ap_const_logic_1 == ap_reg_ppiten_pp2_it1)) & ~(ap_const_lv1_0 == exitcond2_fu_678_p2))) begin
                ap_NS_fsm = ap_ST_st18_fsm_8;
            end else begin
                ap_NS_fsm = ap_ST_pp2_stg0_fsm_7;
            end
        end
        ap_ST_st18_fsm_8 : 
        begin
            ap_NS_fsm = ap_ST_st19_fsm_9;
        end
        ap_ST_st19_fsm_9 : 
        begin
            if ((ap_const_lv1_0 == exitcond3_fu_703_p2)) begin
                ap_NS_fsm = ap_ST_pp3_stg0_fsm_10;
            end else begin
                ap_NS_fsm = ap_ST_pp5_stg0_fsm_22;
            end
        end
        ap_ST_pp3_stg0_fsm_10 : 
        begin
            if ((~((ap_const_logic_1 == ap_sig_cseq_ST_pp3_stg0_fsm_10) & (ap_const_logic_1 == ap_reg_ppiten_pp3_it2) & ~(ap_const_logic_1 == ap_reg_ppiten_pp3_it1)) & ~((ap_const_logic_1 == ap_reg_ppiten_pp3_it0) & ~(ap_const_lv1_0 == exitcond4_fu_709_p2) & ~(ap_const_logic_1 == ap_reg_ppiten_pp3_it1)))) begin
                ap_NS_fsm = ap_ST_pp3_stg1_fsm_11;
            end else if (((ap_const_logic_1 == ap_reg_ppiten_pp3_it0) & ~(ap_const_lv1_0 == exitcond4_fu_709_p2) & ~(ap_const_logic_1 == ap_reg_ppiten_pp3_it1))) begin
                ap_NS_fsm = ap_ST_st27_fsm_13;
            end else begin
                ap_NS_fsm = ap_ST_st27_fsm_13;
            end
        end
        ap_ST_pp3_stg1_fsm_11 : 
        begin
            if (~((ap_const_logic_1 == ap_reg_ppiten_pp3_it0) & ap_sig_bdd_336)) begin
                ap_NS_fsm = ap_ST_pp3_stg2_fsm_12;
            end else begin
                ap_NS_fsm = ap_ST_pp3_stg1_fsm_11;
            end
        end
        ap_ST_pp3_stg2_fsm_12 : 
        begin
            ap_NS_fsm = ap_ST_pp3_stg0_fsm_10;
        end
        ap_ST_st27_fsm_13 : 
        begin
            if (~(rgb_data_out_full_n == ap_const_logic_0)) begin
                ap_NS_fsm = ap_ST_pp4_stg0_fsm_14;
            end else begin
                ap_NS_fsm = ap_ST_st27_fsm_13;
            end
        end
        ap_ST_pp4_stg0_fsm_14 : 
        begin
            if (~((ap_const_logic_1 == ap_reg_ppiten_pp4_it0) & ~(ap_const_lv1_0 == exitcond6_fu_832_p2) & ~(ap_const_logic_1 == ap_reg_ppiten_pp4_it1))) begin
                ap_NS_fsm = ap_ST_pp4_stg1_fsm_15;
            end else begin
                ap_NS_fsm = ap_ST_st39_fsm_18;
            end
        end
        ap_ST_pp4_stg1_fsm_15 : 
        begin
            ap_NS_fsm = ap_ST_pp4_stg2_fsm_16;
        end
        ap_ST_pp4_stg2_fsm_16 : 
        begin
            if ((~((ap_const_logic_1 == ap_reg_ppiten_pp4_it2) & ap_sig_bdd_387) & ~((ap_const_logic_1 == ap_reg_ppiten_pp4_it2) & (ap_const_logic_1 == ap_sig_cseq_ST_pp4_stg2_fsm_16) & ~((ap_const_logic_1 == ap_reg_ppiten_pp4_it2) & ap_sig_bdd_387) & ~(ap_const_logic_1 == ap_reg_ppiten_pp4_it1)))) begin
                ap_NS_fsm = ap_ST_pp4_stg3_fsm_17;
            end else if (((ap_const_logic_1 == ap_reg_ppiten_pp4_it2) & (ap_const_logic_1 == ap_sig_cseq_ST_pp4_stg2_fsm_16) & ~((ap_const_logic_1 == ap_reg_ppiten_pp4_it2) & ap_sig_bdd_387) & ~(ap_const_logic_1 == ap_reg_ppiten_pp4_it1))) begin
                ap_NS_fsm = ap_ST_st39_fsm_18;
            end else begin
                ap_NS_fsm = ap_ST_pp4_stg2_fsm_16;
            end
        end
        ap_ST_pp4_stg3_fsm_17 : 
        begin
            ap_NS_fsm = ap_ST_pp4_stg0_fsm_14;
        end
        ap_ST_st39_fsm_18 : 
        begin
            if (~(rgb_data_out_full_n == ap_const_logic_0)) begin
                ap_NS_fsm = ap_ST_st40_fsm_19;
            end else begin
                ap_NS_fsm = ap_ST_st39_fsm_18;
            end
        end
        ap_ST_st40_fsm_19 : 
        begin
            if (~(ap_const_lv1_0 == exitcond5_fu_1178_p2)) begin
                ap_NS_fsm = ap_ST_st19_fsm_9;
            end else begin
                ap_NS_fsm = ap_ST_st41_fsm_20;
            end
        end
        ap_ST_st41_fsm_20 : 
        begin
            ap_NS_fsm = ap_ST_st42_fsm_21;
        end
        ap_ST_st42_fsm_21 : 
        begin
            ap_NS_fsm = ap_ST_st40_fsm_19;
        end
        ap_ST_pp5_stg0_fsm_22 : 
        begin
            if (~((ap_const_logic_1 == ap_reg_ppiten_pp5_it0) & ~(ap_sig_bdd_468 & (ap_const_logic_1 == ap_reg_ppiten_pp5_it1)) & ~(ap_const_lv1_0 == exitcond8_fu_1227_p2))) begin
                ap_NS_fsm = ap_ST_pp5_stg0_fsm_22;
            end else if (((ap_const_logic_1 == ap_reg_ppiten_pp5_it0) & ~(ap_sig_bdd_468 & (ap_const_logic_1 == ap_reg_ppiten_pp5_it1)) & ~(ap_const_lv1_0 == exitcond8_fu_1227_p2))) begin
                ap_NS_fsm = ap_ST_st45_fsm_23;
            end else begin
                ap_NS_fsm = ap_ST_pp5_stg0_fsm_22;
            end
        end
        ap_ST_st45_fsm_23 : 
        begin
            ap_NS_fsm = ap_ST_st1_fsm_0;
        end
        default : 
        begin
            ap_NS_fsm = 'bx;
        end
    endcase
end


/// ap_rst_n_inv assign process. ///
always @ (ap_rst_n)
begin
    ap_rst_n_inv = ~ap_rst_n;
end

/// ap_sig_bdd_103 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_103 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_A]);
end

/// ap_sig_bdd_1217 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_1217 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_17]);
end

/// ap_sig_bdd_128 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_128 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_4]);
end

/// ap_sig_bdd_150 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_150 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_F]);
end

/// ap_sig_bdd_166 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_166 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_11]);
end

/// ap_sig_bdd_174 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_174 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_14]);
end

/// ap_sig_bdd_200 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_200 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_3]);
end

/// ap_sig_bdd_210 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_210 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_2]);
end

/// ap_sig_bdd_214 assign process. ///
always @ (rgb_data_in_empty_n or exitcond_reg_1284)
begin
    ap_sig_bdd_214 = ((exitcond_reg_1284 == ap_const_lv1_0) & (rgb_data_in_empty_n == ap_const_logic_0));
end

/// ap_sig_bdd_244 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_244 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_6]);
end

/// ap_sig_bdd_254 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_254 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_5]);
end

/// ap_sig_bdd_257 assign process. ///
always @ (rgb_data_in_empty_n or exitcond1_reg_1313)
begin
    ap_sig_bdd_257 = ((ap_const_lv1_0 == exitcond1_reg_1313) & (rgb_data_in_empty_n == ap_const_logic_0));
end

/// ap_sig_bdd_275 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_275 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_7]);
end

/// ap_sig_bdd_282 assign process. ///
always @ (rgb_data_out_full_n or exitcond2_reg_1347)
begin
    ap_sig_bdd_282 = ((rgb_data_out_full_n == ap_const_logic_0) & (ap_const_lv1_0 == exitcond2_reg_1347));
end

/// ap_sig_bdd_299 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_299 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_8]);
end

/// ap_sig_bdd_308 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_308 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_9]);
end

/// ap_sig_bdd_323 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_323 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_C]);
end

/// ap_sig_bdd_333 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_333 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_B]);
end

/// ap_sig_bdd_336 assign process. ///
always @ (rgb_data_in_empty_n or exitcond4_reg_1365)
begin
    ap_sig_bdd_336 = ((ap_const_lv1_0 == exitcond4_reg_1365) & (rgb_data_in_empty_n == ap_const_logic_0));
end

/// ap_sig_bdd_353 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_353 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_E]);
end

/// ap_sig_bdd_383 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_383 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_10]);
end

/// ap_sig_bdd_387 assign process. ///
always @ (rgb_data_out_full_n or ap_reg_ppstg_exitcond6_reg_1394_pp4_it2)
begin
    ap_sig_bdd_387 = ((rgb_data_out_full_n == ap_const_logic_0) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond6_reg_1394_pp4_it2));
end

/// ap_sig_bdd_42 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_42 = (ap_CS_fsm[ap_const_lv32_0] == ap_const_lv1_1);
end

/// ap_sig_bdd_442 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_442 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_13]);
end

/// ap_sig_bdd_462 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_462 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_16]);
end

/// ap_sig_bdd_468 assign process. ///
always @ (rgb_data_out_full_n or exitcond8_reg_1562)
begin
    ap_sig_bdd_468 = ((rgb_data_out_full_n == ap_const_logic_0) & (ap_const_lv1_0 == exitcond8_reg_1562));
end

/// ap_sig_bdd_509 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_509 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_D]);
end

/// ap_sig_bdd_553 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_553 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_12]);
end

/// ap_sig_bdd_561 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_561 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_15]);
end

/// ap_sig_bdd_83 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_83 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_1]);
end
assign edge_val1_fu_1124_p3 = ((tmp_29_fu_1114_p2[0:0]===1'b1)? edge_val_fu_1119_p2: ap_const_lv8_0);
assign edge_val_1_fu_1163_p2 = (edge_val_2_fu_1156_p3 ^ tmp_9_cast_reg_1356);
assign edge_val_2_fu_1156_p3 = ((tmp_34_fu_1152_p2[0:0]===1'b1)? p_edge_val_fu_1145_p3: edge_val1_reg_1514);
assign edge_val_fu_1119_p2 = (tmp_39_reg_1509 ^ ap_const_lv8_FF);
assign edge_weight_fu_1104_p2 = ($signed(x_weight_1_cast_fu_1086_p1) + $signed(y_weight_1_cast_fu_1100_p1));
assign exitcond1_fu_558_p2 = (pix_j_1_phi_fu_311_p4 == ap_const_lv12_800? 1'b1: 1'b0);
assign exitcond2_fu_678_p2 = (p_01_rec_reg_318 == ap_const_lv12_800? 1'b1: 1'b0);
assign exitcond3_fu_703_p2 = (pix_i_reg_329 == ap_const_lv11_438? 1'b1: 1'b0);
assign exitcond4_fu_709_p2 = (pix_j_3_phi_fu_345_p4 == ap_const_lv12_800? 1'b1: 1'b0);
assign exitcond5_fu_1178_p2 = (pix_j_5_reg_376 == ap_const_lv11_780? 1'b1: 1'b0);
assign exitcond6_fu_832_p2 = (p_12_pn_rec_phi_fu_369_p4 == ap_const_lv11_7FE? 1'b1: 1'b0);
assign exitcond8_fu_1227_p2 = (p_34_rec_reg_388 == ap_const_lv12_800? 1'b1: 1'b0);
assign exitcond_fu_443_p2 = (pix_j_phi_fu_299_p4 == ap_const_lv12_800? 1'b1: 1'b0);
assign grp_fu_1239_p0 = ap_const_lv13_19;
assign grp_fu_1239_p1 = grp_fu_1239_p10;
assign grp_fu_1239_p10 = in_B_2_fu_721_p1;
assign grp_fu_1239_p2 = grp_fu_1239_p20;
assign grp_fu_1239_p20 = tmp16_fu_763_p2;
assign grp_fu_1247_p0 = ap_const_lv13_19;
assign grp_fu_1247_p1 = grp_fu_1247_p10;
assign grp_fu_1247_p10 = in_B_1_fu_576_p1;
assign grp_fu_1247_p2 = grp_fu_1247_p20;
assign grp_fu_1247_p20 = tmp11_fu_618_p2;
assign grp_fu_1255_p0 = ap_const_lv13_19;
assign grp_fu_1255_p1 = grp_fu_1255_p10;
assign grp_fu_1255_p10 = in_B_fu_455_p1;
assign grp_fu_1255_p2 = grp_fu_1255_p20;
assign grp_fu_1255_p20 = tmp8_fu_497_p2;
assign grp_fu_417_p4 = {{pixel_fu_140[ap_const_lv32_17 : ap_const_lv32_10]}};
assign in_B_1_fu_576_p1 = pixel_fu_140[7:0];
assign in_B_2_fu_721_p1 = pixel_fu_140[7:0];
assign in_B_fu_455_p1 = pixel_fu_140[7:0];
assign line_buffer_addr10_fu_968_p3 = {{ap_const_lv21_2}, {pix_j_4_reg_353}};
assign line_buffer_addr11_fu_1190_p3 = {{ap_const_lv21_1}, {pix_j_5_reg_376}};
assign line_buffer_addr13_fu_1203_p3 = {{ap_const_lv21_2}, {pix_j_5_reg_376}};
assign line_buffer_addr1_fu_570_p2 = (pix_j_1_phi_fu_311_p4 ^ ap_const_lv12_800);
assign line_buffer_addr2_fu_819_p3 = {{ap_const_lv20_1}, {ap_reg_ppstg_pix_j_3_reg_341_pp3_it1}};
assign line_buffer_addr5_fu_866_p3 = {{ap_const_lv21_1}, {tmp_12_reg_1403}};
assign line_buffer_addr6_fu_878_p3 = {{ap_const_lv21_1}, {pix_j_9_reg_1414}};
assign line_buffer_addr7_fu_898_p3 = {{ap_const_lv21_2}, {tmp_12_reg_1403}};
assign line_buffer_addr8_fu_916_p3 = {{ap_const_lv21_2}, {pix_j_9_reg_1414}};
assign line_buffer_d1 = reg_431;
assign not_tmp_8_fu_690_p2 = (isobelInvert != ap_const_lv32_0? 1'b1: 1'b0);
assign p_23_rec_fu_838_p2 = (p_12_pn_rec_phi_fu_369_p4 + ap_const_lv11_1);
assign p_edge_val_fu_1145_p3 = ((tmp_32_reg_1520[0:0]===1'b1)? ap_const_lv8_FF: ap_const_lv8_0);
assign p_rec3_fu_684_p2 = (p_01_rec_reg_318 + ap_const_lv12_1);
assign p_rec_fu_1233_p2 = (p_34_rec_reg_388 + ap_const_lv12_1);
assign p_shl1_i1_cast_fu_592_p1 = p_shl1_i1_fu_584_p3;
assign p_shl1_i1_fu_584_p3 = {{grp_fu_417_p4}, {ap_const_lv6_0}};
assign p_shl1_i2_cast_fu_737_p1 = p_shl1_i2_fu_729_p3;
assign p_shl1_i2_fu_729_p3 = {{grp_fu_417_p4}, {ap_const_lv6_0}};
assign p_shl1_i_cast_fu_471_p1 = p_shl1_i_fu_463_p3;
assign p_shl1_i_fu_463_p3 = {{grp_fu_417_p4}, {ap_const_lv6_0}};
assign p_shl2_i1_cast_fu_604_p1 = p_shl2_i1_fu_596_p3;
assign p_shl2_i1_fu_596_p3 = {{grp_fu_417_p4}, {ap_const_lv1_0}};
assign p_shl2_i2_cast_fu_749_p1 = p_shl2_i2_fu_741_p3;
assign p_shl2_i2_fu_741_p3 = {{grp_fu_417_p4}, {ap_const_lv1_0}};
assign p_shl2_i_cast_fu_483_p1 = p_shl2_i_fu_475_p3;
assign p_shl2_i_fu_475_p3 = {{grp_fu_417_p4}, {ap_const_lv1_0}};
assign p_shl_i1_cast_fu_636_p1 = p_shl_i1_fu_628_p3;
assign p_shl_i1_fu_628_p3 = {{reg_427}, {ap_const_lv7_0}};
assign p_shl_i2_cast_fu_781_p1 = p_shl_i2_fu_773_p3;
assign p_shl_i2_fu_773_p3 = {{reg_427}, {ap_const_lv7_0}};
assign p_shl_i_cast_fu_515_p1 = p_shl_i_fu_507_p3;
assign p_shl_i_fu_507_p3 = {{reg_427}, {ap_const_lv7_0}};
assign pix_i_1_fu_1216_p2 = (pix_i_reg_329 + ap_const_lv11_1);
assign pix_j_2_fu_449_p2 = (pix_j_phi_fu_299_p4 + ap_const_lv12_1);
assign pix_j_6_fu_564_p2 = (pix_j_1_phi_fu_311_p4 + ap_const_lv12_1);
assign pix_j_7_fu_715_p2 = (pix_j_3_phi_fu_345_p4 + ap_const_lv12_1);
assign pix_j_8_fu_1184_p2 = (pix_j_5_reg_376 + ap_const_lv11_1);
assign pix_j_9_fu_855_p2 = (ap_const_lv11_1 + pix_j_4_phi_fu_357_p4);
assign tmp10_fu_643_p2 = (tmp24_cast_fu_640_p1 + p_shl_i1_cast_fu_636_p1);
assign tmp11_fu_618_p2 = (ap_const_lv9_80 + tmp_2_i1_cast1_fu_608_p1);
assign tmp14_fu_757_p2 = (p_shl1_i2_cast_fu_737_p1 + p_shl2_i2_cast_fu_749_p1);
assign tmp15_fu_788_p2 = (p_shl_i2_cast_fu_781_p1 + tmp28_cast_fu_785_p1);
assign tmp16_fu_763_p2 = (ap_const_lv9_80 + tmp_2_i2_cast1_fu_753_p1);
assign tmp1_cast_fu_943_p1 = $signed(tmp_23_fu_936_p3);
assign tmp20_cast_fu_519_p1 = tmp6_reg_1298;
assign tmp21_cast_fu_528_p1 = tmp9_reg_1303;
assign tmp24_cast_fu_640_p1 = tmp5_reg_1332;
assign tmp25_cast_fu_649_p1 = tmp12_reg_1337;
assign tmp28_cast_fu_785_p1 = tmp14_reg_1379;
assign tmp29_cast_fu_794_p1 = tmp17_reg_1384;
assign tmp2_fu_1022_p2 = (tmp_27_cast_fu_1014_p1 - tmp_28_cast_fu_1018_p1);
assign tmp3_cast_fu_1050_p1 = $signed(tmp_38_fu_1043_p3);
assign tmp5_fu_612_p2 = (p_shl2_i1_cast_fu_604_p1 + p_shl1_i1_cast_fu_592_p1);
assign tmp6_fu_491_p2 = (p_shl1_i_cast_fu_471_p1 + p_shl2_i_cast_fu_483_p1);
assign tmp7_fu_522_p2 = (p_shl_i_cast_fu_515_p1 + tmp20_cast_fu_519_p1);
assign tmp8_fu_497_p2 = (ap_const_lv9_80 + tmp_2_i_cast1_fu_487_p1);
assign tmp_10_fu_827_p1 = line_buffer_addr2_fu_819_p3;
assign tmp_12_fu_844_p2 = ($signed(ap_const_lv11_7FF) + $signed(pix_j_4_phi_fu_357_p4));
assign tmp_13_fu_850_p1 = $unsigned(tmp_12_fu_844_p2);
assign tmp_14_cast_fu_987_p1 = reg_431;
assign tmp_14_fu_861_p1 = pix_j_9_fu_855_p2;
assign tmp_15_fu_873_p1 = line_buffer_addr5_fu_866_p3;
assign tmp_16_cast1_fu_995_p1 = reg_437;
assign tmp_16_cast_fu_928_p1 = reg_431;
assign tmp_16_fu_885_p1 = line_buffer_addr6_fu_878_p3;
assign tmp_17_fu_905_p1 = line_buffer_addr7_fu_898_p3;
assign tmp_18_cast_fu_932_p1 = reg_437;
assign tmp_18_fu_947_p2 = (tmp_18_cast_fu_932_p1 - tmp_16_cast_fu_928_p1);
assign tmp_19_cast_fu_890_p1 = line_buffer_q1;
assign tmp_19_fu_957_p2 = ($signed(tmp1_cast_fu_943_p1) + $signed(tmp_23_cast_cast_fu_953_p1));
assign tmp_20_cast_fu_894_p1 = line_buffer_q0;
assign tmp_20_fu_1003_p2 = ($signed(tmp_19_reg_1451) - $signed(tmp_14_cast_fu_987_p1));
assign tmp_21_cast_fu_991_p1 = reg_431;
assign tmp_21_fu_981_p2 = (tmp_16_cast_fu_928_p1 + tmp_18_cast_fu_932_p1);
assign tmp_22_cast_fu_999_p1 = reg_437;
assign tmp_22_fu_1031_p2 = (tmp_29_cast_fu_1028_p1 - tmp_21_cast_fu_991_p1);
assign tmp_23_cast_cast_fu_953_p1 = $signed(tmp_18_fu_947_p2);
assign tmp_23_fu_936_p3 = {{tmp_reg_1441}, {ap_const_lv1_0}};
assign tmp_24_fu_1037_p2 = (tmp_22_fu_1031_p2 - tmp_22_cast_fu_999_p1);
assign tmp_25_fu_1063_p2 = ($signed(x_weight_reg_1471) > $signed(11'b00000000000)? 1'b1: 1'b0);
assign tmp_26_fu_1068_p2 = ($signed(ap_const_lv11_0) - $signed(x_weight_reg_1471));
assign tmp_27_cast_fu_1014_p1 = line_buffer_q1;
assign tmp_27_fu_1080_p2 = ($signed(y_weight_fu_1057_p2) > $signed(11'b00000000000)? 1'b1: 1'b0);
assign tmp_28_cast_fu_1018_p1 = line_buffer_q0;
assign tmp_28_fu_1089_p2 = ($signed(ap_const_lv11_0) - $signed(y_weight_reg_1488));
assign tmp_29_cast_fu_1028_p1 = tmp_21_reg_1466;
assign tmp_29_fu_1114_p2 = ($signed(edge_weight_reg_1504) < $signed(12'b11111111)? 1'b1: 1'b0);
assign tmp_2_i1_cast1_fu_608_p1 = reg_427;
assign tmp_2_i2_cast1_fu_753_p1 = reg_427;
assign tmp_2_i_cast1_fu_487_p1 = reg_427;
assign tmp_30_fu_923_p1 = line_buffer_addr8_fu_916_p3;
assign tmp_31_cast_cast_fu_1054_p1 = $signed(tmp_24_reg_1483);
assign tmp_31_fu_1132_p1 = edge_val1_reg_1514;
assign tmp_32_fu_1135_p2 = ($signed(tmp_31_fu_1132_p1) > $signed(imaxsobelSensitivity)? 1'b1: 1'b0);
assign tmp_33_fu_1140_p2 = ($signed(tmp_31_fu_1132_p1) < $signed(iminsobelSensitivity)? 1'b1: 1'b0);
assign tmp_34_fu_1152_p2 = (tmp_32_reg_1520 | tmp_33_reg_1526);
assign tmp_35_fu_1168_p5 = {{{{{{ap_const_lv8_FF}, {edge_val_1_reg_1531}}}, {edge_val_1_reg_1531}}}, {edge_val_1_reg_1531}};
assign tmp_36_fu_963_p1 = pix_j_4_reg_353;
assign tmp_37_fu_976_p1 = line_buffer_addr10_fu_968_p3;
assign tmp_38_fu_1043_p3 = {{tmp2_reg_1478}, {ap_const_lv1_0}};
assign tmp_39_fu_1110_p1 = edge_weight_fu_1104_p2[7:0];
assign tmp_3_fu_674_p1 = ap_reg_ppstg_line_buffer_addr1_reg_1322_pp1_it1;
assign tmp_40_fu_1198_p1 = line_buffer_addr11_fu_1190_p3;
assign tmp_41_fu_1222_p1 = pix_j_5_reg_376;
assign tmp_42_fu_1211_p1 = line_buffer_addr13_fu_1203_p3;
assign tmp_5_fu_553_p1 = ap_reg_ppstg_pix_j_reg_295_pp0_it1;
assign tmp_8_i1_fu_652_p2 = (tmp25_cast_fu_649_p1 + tmp10_fu_643_p2);
assign tmp_8_i2_fu_797_p2 = (tmp15_fu_788_p2 + tmp29_cast_fu_794_p1);
assign tmp_8_i_fu_531_p2 = (tmp7_fu_522_p2 + tmp21_cast_fu_528_p1);
assign tmp_9_cast_fu_695_p3 = ((not_tmp_8_fu_690_p2[0:0]===1'b1)? ap_const_lv8_FF: ap_const_lv8_0);
assign tmp_fu_910_p2 = (tmp_20_cast_fu_894_p1 - tmp_19_cast_fu_890_p1);
assign x_weight_1_cast_fu_1086_p1 = $signed(x_weight_1_reg_1494);
assign x_weight_1_fu_1073_p3 = ((tmp_25_fu_1063_p2[0:0]===1'b1)? x_weight_reg_1471: tmp_26_fu_1068_p2);
assign x_weight_fu_1008_p2 = ($signed(tmp_20_fu_1003_p2) + $signed(tmp_16_cast1_fu_995_p1));
assign y_1_fu_668_p2 = (ap_const_lv8_10 + tmp_i1_reg_1342);
assign y_2_fu_813_p2 = (ap_const_lv8_10 + tmp_i2_reg_1389);
assign y_fu_547_p2 = (ap_const_lv8_10 + tmp_i_reg_1308);
assign y_weight_1_cast_fu_1100_p1 = $signed(y_weight_1_fu_1094_p3);
assign y_weight_1_fu_1094_p3 = ((tmp_27_reg_1499[0:0]===1'b1)? y_weight_reg_1488: tmp_28_fu_1089_p2);
assign y_weight_fu_1057_p2 = ($signed(tmp3_cast_fu_1050_p1) + $signed(tmp_31_cast_cast_fu_1054_p1));
always @ (posedge ap_clk)
begin
    tmp6_reg_1298[0] <= 1'b0;
    tmp5_reg_1332[0] <= 1'b0;
    tmp14_reg_1379[0] <= 1'b0;
    line_buffer_addr_11_reg_1546[12:11] <= 2'b01;
end



endmodule //img_process

