// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.2_hlssdsoc
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ==============================================================


`timescale 1 ns / 1 ps

(* use_dsp48 = "yes" *) module img_process_mac_muladd_6ns_8ns_9ns_13_3_DSP48_0(clk, rst, ce, a, b, c, p);
input clk;
input rst;
input ce;
input [6 - 1 : 0] a; 
input [8 - 1 : 0] b; 
input [9 - 1 : 0] c; 
output [13 - 1 : 0] p; 

reg [6 - 1 : 0] a_reg; 
reg [8 - 1 : 0] b_reg; 
reg [14 - 1 : 0] m_reg; 

always @ (posedge clk) begin
    if (rst) begin
        a_reg <= 0;
        b_reg <= 0;
        m_reg <= 0;
    end else
    if (ce) begin
        a_reg <= a;
        b_reg <= b;
        m_reg <= $unsigned (a_reg) * $unsigned (b_reg);
    end
end

assign p =  $unsigned (m_reg) + $unsigned ({1'b0, c});

endmodule

`timescale 1 ns / 1 ps
module img_process_mac_muladd_6ns_8ns_9ns_13_3(
    clk,
    reset,
    ce,
    din0,
    din1,
    din2,
    dout);

parameter ID = 32'd1;
parameter NUM_STAGE = 32'd1;
parameter din0_WIDTH = 32'd1;
parameter din1_WIDTH = 32'd1;
parameter din2_WIDTH = 32'd1;
parameter dout_WIDTH = 32'd1;
input clk;
input reset;
input ce;
input[din0_WIDTH - 1:0] din0;
input[din1_WIDTH - 1:0] din1;
input[din2_WIDTH - 1:0] din2;
output[dout_WIDTH - 1:0] dout;



img_process_mac_muladd_6ns_8ns_9ns_13_3_DSP48_0 img_process_mac_muladd_6ns_8ns_9ns_13_3_DSP48_0_U(
    .clk( clk ),
    .rst( reset ),
    .ce( ce ),
    .a( din0 ),
    .b( din1 ),
    .c( din2 ),
    .p( dout ));

endmodule

